// Code generated by ent, DO NOT EDIT.

package alertrule

import (
	"fmt"
	"time"
	"volaticloud/internal/enum"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the alertrule type in the database.
	Label = "alert_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAlertType holds the string denoting the alert_type field in the database.
	FieldAlertType = "alert_type"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldConditions holds the string denoting the conditions field in the database.
	FieldConditions = "conditions"
	// FieldDeliveryMode holds the string denoting the delivery_mode field in the database.
	FieldDeliveryMode = "delivery_mode"
	// FieldBatchIntervalMinutes holds the string denoting the batch_interval_minutes field in the database.
	FieldBatchIntervalMinutes = "batch_interval_minutes"
	// FieldRecipients holds the string denoting the recipients field in the database.
	FieldRecipients = "recipients"
	// FieldBotModeFilter holds the string denoting the bot_mode_filter field in the database.
	FieldBotModeFilter = "bot_mode_filter"
	// FieldCooldownMinutes holds the string denoting the cooldown_minutes field in the database.
	FieldCooldownMinutes = "cooldown_minutes"
	// FieldLastTriggeredAt holds the string denoting the last_triggered_at field in the database.
	FieldLastTriggeredAt = "last_triggered_at"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the alertrule in the database.
	Table = "alert_rules"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "alert_events"
	// EventsInverseTable is the table name for the AlertEvent entity.
	// It exists in this package in order to avoid circular dependency with the "alertevent" package.
	EventsInverseTable = "alert_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "rule_id"
)

// Columns holds all SQL columns for alertrule fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldName,
	FieldAlertType,
	FieldSeverity,
	FieldEnabled,
	FieldResourceType,
	FieldResourceID,
	FieldConditions,
	FieldDeliveryMode,
	FieldBatchIntervalMinutes,
	FieldRecipients,
	FieldBotModeFilter,
	FieldCooldownMinutes,
	FieldLastTriggeredAt,
	FieldOwnerID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "volaticloud/internal/ent/runtime"
var (
	Interceptors [1]ent.Interceptor
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultBatchIntervalMinutes holds the default value on creation for the "batch_interval_minutes" field.
	DefaultBatchIntervalMinutes int
	// DefaultRecipients holds the default value on creation for the "recipients" field.
	DefaultRecipients []string
	// DefaultCooldownMinutes holds the default value on creation for the "cooldown_minutes" field.
	DefaultCooldownMinutes int
	// OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	OwnerIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// AlertTypeValidator is a validator for the "alert_type" field enum values. It is called by the builders before save.
func AlertTypeValidator(at enum.AlertType) error {
	switch at {
	case "status_change", "trade_opened", "trade_closed", "large_profit_loss", "daily_loss_limit", "drawdown_threshold", "profit_target", "connection_issue", "backtest_completed", "backtest_failed":
		return nil
	default:
		return fmt.Errorf("alertrule: invalid enum value for alert_type field: %q", at)
	}
}

const DefaultSeverity enum.AlertSeverity = "info"

// SeverityValidator is a validator for the "severity" field enum values. It is called by the builders before save.
func SeverityValidator(s enum.AlertSeverity) error {
	switch s {
	case "critical", "warning", "info":
		return nil
	default:
		return fmt.Errorf("alertrule: invalid enum value for severity field: %q", s)
	}
}

// ResourceTypeValidator is a validator for the "resource_type" field enum values. It is called by the builders before save.
func ResourceTypeValidator(rt enum.AlertResourceType) error {
	switch rt {
	case "organization", "bot", "strategy", "runner":
		return nil
	default:
		return fmt.Errorf("alertrule: invalid enum value for resource_type field: %q", rt)
	}
}

const DefaultDeliveryMode enum.AlertDeliveryMode = "immediate"

// DeliveryModeValidator is a validator for the "delivery_mode" field enum values. It is called by the builders before save.
func DeliveryModeValidator(dm enum.AlertDeliveryMode) error {
	switch dm {
	case "immediate", "batched":
		return nil
	default:
		return fmt.Errorf("alertrule: invalid enum value for delivery_mode field: %q", dm)
	}
}

const DefaultBotModeFilter enum.AlertBotModeFilter = "all"

// BotModeFilterValidator is a validator for the "bot_mode_filter" field enum values. It is called by the builders before save.
func BotModeFilterValidator(bmf enum.AlertBotModeFilter) error {
	switch bmf {
	case "all", "live", "dry_run":
		return nil
	default:
		return fmt.Errorf("alertrule: invalid enum value for bot_mode_filter field: %q", bmf)
	}
}

// OrderOption defines the ordering options for the AlertRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAlertType orders the results by the alert_type field.
func ByAlertType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertType, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByDeliveryMode orders the results by the delivery_mode field.
func ByDeliveryMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryMode, opts...).ToFunc()
}

// ByBatchIntervalMinutes orders the results by the batch_interval_minutes field.
func ByBatchIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchIntervalMinutes, opts...).ToFunc()
}

// ByBotModeFilter orders the results by the bot_mode_filter field.
func ByBotModeFilter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBotModeFilter, opts...).ToFunc()
}

// ByCooldownMinutes orders the results by the cooldown_minutes field.
func ByCooldownMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownMinutes, opts...).ToFunc()
}

// ByLastTriggeredAt orders the results by the last_triggered_at field.
func ByLastTriggeredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTriggeredAt, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}

var (
	// enum.AlertType must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.AlertType)(nil)
	// enum.AlertType must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.AlertType)(nil)
)

var (
	// enum.AlertSeverity must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.AlertSeverity)(nil)
	// enum.AlertSeverity must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.AlertSeverity)(nil)
)

var (
	// enum.AlertResourceType must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.AlertResourceType)(nil)
	// enum.AlertResourceType must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.AlertResourceType)(nil)
)

var (
	// enum.AlertDeliveryMode must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.AlertDeliveryMode)(nil)
	// enum.AlertDeliveryMode must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.AlertDeliveryMode)(nil)
)

var (
	// enum.AlertBotModeFilter must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.AlertBotModeFilter)(nil)
	// enum.AlertBotModeFilter must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.AlertBotModeFilter)(nil)
)
