version: "2"
run:
  tests: false
linters:
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: Use os or io package instead of deprecated io/ioutil
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - io.Copy
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - (*os.File).Close
        - (io.Closer).Close
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - all
        path: internal/ent/
      - linters:
          - all
        path: internal/graph/generated\.go
      - linters:
          - all
        path: internal/graph/model/
      - linters:
          - all
        path: internal/graph/ent\.resolvers\.go
      - linters:
          - gosec
        text: 'G404: Use of weak random number generator'
      - linters:
          - staticcheck
        text: 'S1009:'
      - linters:
          - errcheck
        text: Error return value.*not checked
        source: w\.Write|io\.WriteString|d\.client\.ContainerRemove
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  settings:
    goimports:
      local-prefixes:
        - volaticloud
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
