version: '2'

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - internal/ent
    - internal/graph/model
  skip-files:
    - ".*\\.generated\\.go$"
    - ".*/ent/.*\\.go$"
    - ".*/graph/generated\\.go$"
    - ".*/graph/ent\\.resolvers\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow # Too many false positives

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 140

  goimports:
    local-prefixes: anytrade

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  funlen:
    lines: 100
    statements: 50

  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "Use os or io package instead of deprecated io/ioutil"

linters:
  enable-all: false
  disable-all: false
  # Use default recommended linters
  # Additional linters can be enabled manually

issues:
  exclude-rules:
    # Exclude all linters from generated ENT code
    - path: internal/ent/
      linters:
        - all

    # Exclude all linters from generated GraphQL code
    - path: internal/graph/generated\.go
      linters:
        - all

    # Exclude all linters from GraphQL models
    - path: internal/graph/model/
      linters:
        - all

    # Exclude all linters from ENT resolvers (partially generated)
    - path: internal/graph/ent\.resolvers\.go
      linters:
        - all

    # Exclude known false positives
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
