// Code generated by ent, DO NOT EDIT.

package resourceusageaggregation

import (
	"time"
	"volaticloud/internal/ent/predicate"
	"volaticloud/internal/enum"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldDeletedAt, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldResourceID, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldOwnerID, v))
}

// RunnerID applies equality check predicate on the "runner_id" field. It's identical to RunnerIDEQ.
func RunnerID(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldRunnerID, v))
}

// BucketStart applies equality check predicate on the "bucket_start" field. It's identical to BucketStartEQ.
func BucketStart(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBucketStart, v))
}

// BucketEnd applies equality check predicate on the "bucket_end" field. It's identical to BucketEndEQ.
func BucketEnd(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBucketEnd, v))
}

// CPUCoreSeconds applies equality check predicate on the "cpu_core_seconds" field. It's identical to CPUCoreSecondsEQ.
func CPUCoreSeconds(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCPUCoreSeconds, v))
}

// CPUAvgPercent applies equality check predicate on the "cpu_avg_percent" field. It's identical to CPUAvgPercentEQ.
func CPUAvgPercent(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCPUAvgPercent, v))
}

// CPUMaxPercent applies equality check predicate on the "cpu_max_percent" field. It's identical to CPUMaxPercentEQ.
func CPUMaxPercent(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCPUMaxPercent, v))
}

// MemoryGBSeconds applies equality check predicate on the "memory_gb_seconds" field. It's identical to MemoryGBSecondsEQ.
func MemoryGBSeconds(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldMemoryGBSeconds, v))
}

// MemoryAvgBytes applies equality check predicate on the "memory_avg_bytes" field. It's identical to MemoryAvgBytesEQ.
func MemoryAvgBytes(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldMemoryAvgBytes, v))
}

// MemoryMaxBytes applies equality check predicate on the "memory_max_bytes" field. It's identical to MemoryMaxBytesEQ.
func MemoryMaxBytes(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldMemoryMaxBytes, v))
}

// NetworkRxBytes applies equality check predicate on the "network_rx_bytes" field. It's identical to NetworkRxBytesEQ.
func NetworkRxBytes(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldNetworkRxBytes, v))
}

// NetworkTxBytes applies equality check predicate on the "network_tx_bytes" field. It's identical to NetworkTxBytesEQ.
func NetworkTxBytes(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldNetworkTxBytes, v))
}

// BlockReadBytes applies equality check predicate on the "block_read_bytes" field. It's identical to BlockReadBytesEQ.
func BlockReadBytes(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBlockReadBytes, v))
}

// BlockWriteBytes applies equality check predicate on the "block_write_bytes" field. It's identical to BlockWriteBytesEQ.
func BlockWriteBytes(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBlockWriteBytes, v))
}

// SampleCount applies equality check predicate on the "sample_count" field. It's identical to SampleCountEQ.
func SampleCount(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldSampleCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCreatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotNull(FieldDeletedAt))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v enum.ResourceType) predicate.ResourceUsageAggregation {
	vc := v
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldResourceType, vc))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v enum.ResourceType) predicate.ResourceUsageAggregation {
	vc := v
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldResourceType, vc))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...enum.ResourceType) predicate.ResourceUsageAggregation {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldResourceType, v...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...enum.ResourceType) predicate.ResourceUsageAggregation {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldResourceType, v...))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldResourceID, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldContainsFold(FieldOwnerID, v))
}

// RunnerIDEQ applies the EQ predicate on the "runner_id" field.
func RunnerIDEQ(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldRunnerID, v))
}

// RunnerIDNEQ applies the NEQ predicate on the "runner_id" field.
func RunnerIDNEQ(v uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldRunnerID, v))
}

// RunnerIDIn applies the In predicate on the "runner_id" field.
func RunnerIDIn(vs ...uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldRunnerID, vs...))
}

// RunnerIDNotIn applies the NotIn predicate on the "runner_id" field.
func RunnerIDNotIn(vs ...uuid.UUID) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldRunnerID, vs...))
}

// GranularityEQ applies the EQ predicate on the "granularity" field.
func GranularityEQ(v enum.AggregationGranularity) predicate.ResourceUsageAggregation {
	vc := v
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldGranularity, vc))
}

// GranularityNEQ applies the NEQ predicate on the "granularity" field.
func GranularityNEQ(v enum.AggregationGranularity) predicate.ResourceUsageAggregation {
	vc := v
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldGranularity, vc))
}

// GranularityIn applies the In predicate on the "granularity" field.
func GranularityIn(vs ...enum.AggregationGranularity) predicate.ResourceUsageAggregation {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldGranularity, v...))
}

// GranularityNotIn applies the NotIn predicate on the "granularity" field.
func GranularityNotIn(vs ...enum.AggregationGranularity) predicate.ResourceUsageAggregation {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldGranularity, v...))
}

// BucketStartEQ applies the EQ predicate on the "bucket_start" field.
func BucketStartEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBucketStart, v))
}

// BucketStartNEQ applies the NEQ predicate on the "bucket_start" field.
func BucketStartNEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldBucketStart, v))
}

// BucketStartIn applies the In predicate on the "bucket_start" field.
func BucketStartIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldBucketStart, vs...))
}

// BucketStartNotIn applies the NotIn predicate on the "bucket_start" field.
func BucketStartNotIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldBucketStart, vs...))
}

// BucketStartGT applies the GT predicate on the "bucket_start" field.
func BucketStartGT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldBucketStart, v))
}

// BucketStartGTE applies the GTE predicate on the "bucket_start" field.
func BucketStartGTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldBucketStart, v))
}

// BucketStartLT applies the LT predicate on the "bucket_start" field.
func BucketStartLT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldBucketStart, v))
}

// BucketStartLTE applies the LTE predicate on the "bucket_start" field.
func BucketStartLTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldBucketStart, v))
}

// BucketEndEQ applies the EQ predicate on the "bucket_end" field.
func BucketEndEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBucketEnd, v))
}

// BucketEndNEQ applies the NEQ predicate on the "bucket_end" field.
func BucketEndNEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldBucketEnd, v))
}

// BucketEndIn applies the In predicate on the "bucket_end" field.
func BucketEndIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldBucketEnd, vs...))
}

// BucketEndNotIn applies the NotIn predicate on the "bucket_end" field.
func BucketEndNotIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldBucketEnd, vs...))
}

// BucketEndGT applies the GT predicate on the "bucket_end" field.
func BucketEndGT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldBucketEnd, v))
}

// BucketEndGTE applies the GTE predicate on the "bucket_end" field.
func BucketEndGTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldBucketEnd, v))
}

// BucketEndLT applies the LT predicate on the "bucket_end" field.
func BucketEndLT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldBucketEnd, v))
}

// BucketEndLTE applies the LTE predicate on the "bucket_end" field.
func BucketEndLTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldBucketEnd, v))
}

// CPUCoreSecondsEQ applies the EQ predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCPUCoreSeconds, v))
}

// CPUCoreSecondsNEQ applies the NEQ predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsNEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldCPUCoreSeconds, v))
}

// CPUCoreSecondsIn applies the In predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldCPUCoreSeconds, vs...))
}

// CPUCoreSecondsNotIn applies the NotIn predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsNotIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldCPUCoreSeconds, vs...))
}

// CPUCoreSecondsGT applies the GT predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsGT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldCPUCoreSeconds, v))
}

// CPUCoreSecondsGTE applies the GTE predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsGTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldCPUCoreSeconds, v))
}

// CPUCoreSecondsLT applies the LT predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsLT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldCPUCoreSeconds, v))
}

// CPUCoreSecondsLTE applies the LTE predicate on the "cpu_core_seconds" field.
func CPUCoreSecondsLTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldCPUCoreSeconds, v))
}

// CPUAvgPercentEQ applies the EQ predicate on the "cpu_avg_percent" field.
func CPUAvgPercentEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCPUAvgPercent, v))
}

// CPUAvgPercentNEQ applies the NEQ predicate on the "cpu_avg_percent" field.
func CPUAvgPercentNEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldCPUAvgPercent, v))
}

// CPUAvgPercentIn applies the In predicate on the "cpu_avg_percent" field.
func CPUAvgPercentIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldCPUAvgPercent, vs...))
}

// CPUAvgPercentNotIn applies the NotIn predicate on the "cpu_avg_percent" field.
func CPUAvgPercentNotIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldCPUAvgPercent, vs...))
}

// CPUAvgPercentGT applies the GT predicate on the "cpu_avg_percent" field.
func CPUAvgPercentGT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldCPUAvgPercent, v))
}

// CPUAvgPercentGTE applies the GTE predicate on the "cpu_avg_percent" field.
func CPUAvgPercentGTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldCPUAvgPercent, v))
}

// CPUAvgPercentLT applies the LT predicate on the "cpu_avg_percent" field.
func CPUAvgPercentLT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldCPUAvgPercent, v))
}

// CPUAvgPercentLTE applies the LTE predicate on the "cpu_avg_percent" field.
func CPUAvgPercentLTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldCPUAvgPercent, v))
}

// CPUMaxPercentEQ applies the EQ predicate on the "cpu_max_percent" field.
func CPUMaxPercentEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCPUMaxPercent, v))
}

// CPUMaxPercentNEQ applies the NEQ predicate on the "cpu_max_percent" field.
func CPUMaxPercentNEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldCPUMaxPercent, v))
}

// CPUMaxPercentIn applies the In predicate on the "cpu_max_percent" field.
func CPUMaxPercentIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldCPUMaxPercent, vs...))
}

// CPUMaxPercentNotIn applies the NotIn predicate on the "cpu_max_percent" field.
func CPUMaxPercentNotIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldCPUMaxPercent, vs...))
}

// CPUMaxPercentGT applies the GT predicate on the "cpu_max_percent" field.
func CPUMaxPercentGT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldCPUMaxPercent, v))
}

// CPUMaxPercentGTE applies the GTE predicate on the "cpu_max_percent" field.
func CPUMaxPercentGTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldCPUMaxPercent, v))
}

// CPUMaxPercentLT applies the LT predicate on the "cpu_max_percent" field.
func CPUMaxPercentLT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldCPUMaxPercent, v))
}

// CPUMaxPercentLTE applies the LTE predicate on the "cpu_max_percent" field.
func CPUMaxPercentLTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldCPUMaxPercent, v))
}

// MemoryGBSecondsEQ applies the EQ predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldMemoryGBSeconds, v))
}

// MemoryGBSecondsNEQ applies the NEQ predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsNEQ(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldMemoryGBSeconds, v))
}

// MemoryGBSecondsIn applies the In predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldMemoryGBSeconds, vs...))
}

// MemoryGBSecondsNotIn applies the NotIn predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsNotIn(vs ...float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldMemoryGBSeconds, vs...))
}

// MemoryGBSecondsGT applies the GT predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsGT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldMemoryGBSeconds, v))
}

// MemoryGBSecondsGTE applies the GTE predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsGTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldMemoryGBSeconds, v))
}

// MemoryGBSecondsLT applies the LT predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsLT(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldMemoryGBSeconds, v))
}

// MemoryGBSecondsLTE applies the LTE predicate on the "memory_gb_seconds" field.
func MemoryGBSecondsLTE(v float64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldMemoryGBSeconds, v))
}

// MemoryAvgBytesEQ applies the EQ predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldMemoryAvgBytes, v))
}

// MemoryAvgBytesNEQ applies the NEQ predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesNEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldMemoryAvgBytes, v))
}

// MemoryAvgBytesIn applies the In predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldMemoryAvgBytes, vs...))
}

// MemoryAvgBytesNotIn applies the NotIn predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesNotIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldMemoryAvgBytes, vs...))
}

// MemoryAvgBytesGT applies the GT predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesGT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldMemoryAvgBytes, v))
}

// MemoryAvgBytesGTE applies the GTE predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesGTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldMemoryAvgBytes, v))
}

// MemoryAvgBytesLT applies the LT predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesLT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldMemoryAvgBytes, v))
}

// MemoryAvgBytesLTE applies the LTE predicate on the "memory_avg_bytes" field.
func MemoryAvgBytesLTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldMemoryAvgBytes, v))
}

// MemoryMaxBytesEQ applies the EQ predicate on the "memory_max_bytes" field.
func MemoryMaxBytesEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldMemoryMaxBytes, v))
}

// MemoryMaxBytesNEQ applies the NEQ predicate on the "memory_max_bytes" field.
func MemoryMaxBytesNEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldMemoryMaxBytes, v))
}

// MemoryMaxBytesIn applies the In predicate on the "memory_max_bytes" field.
func MemoryMaxBytesIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldMemoryMaxBytes, vs...))
}

// MemoryMaxBytesNotIn applies the NotIn predicate on the "memory_max_bytes" field.
func MemoryMaxBytesNotIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldMemoryMaxBytes, vs...))
}

// MemoryMaxBytesGT applies the GT predicate on the "memory_max_bytes" field.
func MemoryMaxBytesGT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldMemoryMaxBytes, v))
}

// MemoryMaxBytesGTE applies the GTE predicate on the "memory_max_bytes" field.
func MemoryMaxBytesGTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldMemoryMaxBytes, v))
}

// MemoryMaxBytesLT applies the LT predicate on the "memory_max_bytes" field.
func MemoryMaxBytesLT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldMemoryMaxBytes, v))
}

// MemoryMaxBytesLTE applies the LTE predicate on the "memory_max_bytes" field.
func MemoryMaxBytesLTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldMemoryMaxBytes, v))
}

// NetworkRxBytesEQ applies the EQ predicate on the "network_rx_bytes" field.
func NetworkRxBytesEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldNetworkRxBytes, v))
}

// NetworkRxBytesNEQ applies the NEQ predicate on the "network_rx_bytes" field.
func NetworkRxBytesNEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldNetworkRxBytes, v))
}

// NetworkRxBytesIn applies the In predicate on the "network_rx_bytes" field.
func NetworkRxBytesIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldNetworkRxBytes, vs...))
}

// NetworkRxBytesNotIn applies the NotIn predicate on the "network_rx_bytes" field.
func NetworkRxBytesNotIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldNetworkRxBytes, vs...))
}

// NetworkRxBytesGT applies the GT predicate on the "network_rx_bytes" field.
func NetworkRxBytesGT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldNetworkRxBytes, v))
}

// NetworkRxBytesGTE applies the GTE predicate on the "network_rx_bytes" field.
func NetworkRxBytesGTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldNetworkRxBytes, v))
}

// NetworkRxBytesLT applies the LT predicate on the "network_rx_bytes" field.
func NetworkRxBytesLT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldNetworkRxBytes, v))
}

// NetworkRxBytesLTE applies the LTE predicate on the "network_rx_bytes" field.
func NetworkRxBytesLTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldNetworkRxBytes, v))
}

// NetworkTxBytesEQ applies the EQ predicate on the "network_tx_bytes" field.
func NetworkTxBytesEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldNetworkTxBytes, v))
}

// NetworkTxBytesNEQ applies the NEQ predicate on the "network_tx_bytes" field.
func NetworkTxBytesNEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldNetworkTxBytes, v))
}

// NetworkTxBytesIn applies the In predicate on the "network_tx_bytes" field.
func NetworkTxBytesIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldNetworkTxBytes, vs...))
}

// NetworkTxBytesNotIn applies the NotIn predicate on the "network_tx_bytes" field.
func NetworkTxBytesNotIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldNetworkTxBytes, vs...))
}

// NetworkTxBytesGT applies the GT predicate on the "network_tx_bytes" field.
func NetworkTxBytesGT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldNetworkTxBytes, v))
}

// NetworkTxBytesGTE applies the GTE predicate on the "network_tx_bytes" field.
func NetworkTxBytesGTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldNetworkTxBytes, v))
}

// NetworkTxBytesLT applies the LT predicate on the "network_tx_bytes" field.
func NetworkTxBytesLT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldNetworkTxBytes, v))
}

// NetworkTxBytesLTE applies the LTE predicate on the "network_tx_bytes" field.
func NetworkTxBytesLTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldNetworkTxBytes, v))
}

// BlockReadBytesEQ applies the EQ predicate on the "block_read_bytes" field.
func BlockReadBytesEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBlockReadBytes, v))
}

// BlockReadBytesNEQ applies the NEQ predicate on the "block_read_bytes" field.
func BlockReadBytesNEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldBlockReadBytes, v))
}

// BlockReadBytesIn applies the In predicate on the "block_read_bytes" field.
func BlockReadBytesIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldBlockReadBytes, vs...))
}

// BlockReadBytesNotIn applies the NotIn predicate on the "block_read_bytes" field.
func BlockReadBytesNotIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldBlockReadBytes, vs...))
}

// BlockReadBytesGT applies the GT predicate on the "block_read_bytes" field.
func BlockReadBytesGT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldBlockReadBytes, v))
}

// BlockReadBytesGTE applies the GTE predicate on the "block_read_bytes" field.
func BlockReadBytesGTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldBlockReadBytes, v))
}

// BlockReadBytesLT applies the LT predicate on the "block_read_bytes" field.
func BlockReadBytesLT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldBlockReadBytes, v))
}

// BlockReadBytesLTE applies the LTE predicate on the "block_read_bytes" field.
func BlockReadBytesLTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldBlockReadBytes, v))
}

// BlockWriteBytesEQ applies the EQ predicate on the "block_write_bytes" field.
func BlockWriteBytesEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldBlockWriteBytes, v))
}

// BlockWriteBytesNEQ applies the NEQ predicate on the "block_write_bytes" field.
func BlockWriteBytesNEQ(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldBlockWriteBytes, v))
}

// BlockWriteBytesIn applies the In predicate on the "block_write_bytes" field.
func BlockWriteBytesIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldBlockWriteBytes, vs...))
}

// BlockWriteBytesNotIn applies the NotIn predicate on the "block_write_bytes" field.
func BlockWriteBytesNotIn(vs ...int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldBlockWriteBytes, vs...))
}

// BlockWriteBytesGT applies the GT predicate on the "block_write_bytes" field.
func BlockWriteBytesGT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldBlockWriteBytes, v))
}

// BlockWriteBytesGTE applies the GTE predicate on the "block_write_bytes" field.
func BlockWriteBytesGTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldBlockWriteBytes, v))
}

// BlockWriteBytesLT applies the LT predicate on the "block_write_bytes" field.
func BlockWriteBytesLT(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldBlockWriteBytes, v))
}

// BlockWriteBytesLTE applies the LTE predicate on the "block_write_bytes" field.
func BlockWriteBytesLTE(v int64) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldBlockWriteBytes, v))
}

// SampleCountEQ applies the EQ predicate on the "sample_count" field.
func SampleCountEQ(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldSampleCount, v))
}

// SampleCountNEQ applies the NEQ predicate on the "sample_count" field.
func SampleCountNEQ(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldSampleCount, v))
}

// SampleCountIn applies the In predicate on the "sample_count" field.
func SampleCountIn(vs ...int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldSampleCount, vs...))
}

// SampleCountNotIn applies the NotIn predicate on the "sample_count" field.
func SampleCountNotIn(vs ...int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldSampleCount, vs...))
}

// SampleCountGT applies the GT predicate on the "sample_count" field.
func SampleCountGT(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldSampleCount, v))
}

// SampleCountGTE applies the GTE predicate on the "sample_count" field.
func SampleCountGTE(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldSampleCount, v))
}

// SampleCountLT applies the LT predicate on the "sample_count" field.
func SampleCountLT(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldSampleCount, v))
}

// SampleCountLTE applies the LTE predicate on the "sample_count" field.
func SampleCountLTE(v int) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldSampleCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRunner applies the HasEdge predicate on the "runner" edge.
func HasRunner() predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RunnerTable, RunnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRunnerWith applies the HasEdge predicate on the "runner" edge with a given conditions (other predicates).
func HasRunnerWith(preds ...predicate.BotRunner) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(func(s *sql.Selector) {
		step := newRunnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResourceUsageAggregation) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResourceUsageAggregation) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResourceUsageAggregation) predicate.ResourceUsageAggregation {
	return predicate.ResourceUsageAggregation(sql.NotPredicates(p))
}
