// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"volaticloud/internal/ent/alertrule"
	"volaticloud/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlertRuleDelete is the builder for deleting a AlertRule entity.
type AlertRuleDelete struct {
	config
	hooks    []Hook
	mutation *AlertRuleMutation
}

// Where appends a list predicates to the AlertRuleDelete builder.
func (_d *AlertRuleDelete) Where(ps ...predicate.AlertRule) *AlertRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AlertRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AlertRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AlertRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(alertrule.Table, sqlgraph.NewFieldSpec(alertrule.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AlertRuleDeleteOne is the builder for deleting a single AlertRule entity.
type AlertRuleDeleteOne struct {
	_d *AlertRuleDelete
}

// Where appends a list predicates to the AlertRuleDelete builder.
func (_d *AlertRuleDeleteOne) Where(ps ...predicate.AlertRule) *AlertRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AlertRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{alertrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AlertRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
