// Code generated by ent, DO NOT EDIT.

package ent

import (
	"anytrade/internal/ent/bot"
	"anytrade/internal/ent/botrunner"
	"anytrade/internal/ent/exchange"
	"anytrade/internal/ent/strategy"
	"anytrade/internal/enum"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Bot is the model entity for the Bot schema.
type Bot struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Bot display name
	Name string `json:"name,omitempty"`
	// Bot lifecycle status
	Status enum.BotStatus `json:"status,omitempty"`
	// Trading mode (dry-run or live)
	Mode enum.BotMode `json:"mode,omitempty"`
	// Runner-specific identifier (container ID, pod name, etc.)
	ContainerID string `json:"container_id,omitempty"`
	// Complete freqtrade bot configuration (stake, pairlists, pricing, api_server, etc.)
	Config map[string]interface{} `json:"config,omitempty"`
	// Freqtrade Docker image version tag
	FreqtradeVersion string `json:"freqtrade_version,omitempty"`
	// Last successful health check
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// Last error message if status is error
	ErrorMessage string `json:"error_message,omitempty"`
	// Foreign key to exchange (provides credentials)
	ExchangeID uuid.UUID `json:"exchange_id,omitempty"`
	// Foreign key to strategy (provides code)
	StrategyID uuid.UUID `json:"strategy_id,omitempty"`
	// Foreign key to runner (provides execution environment)
	RunnerID uuid.UUID `json:"runner_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BotQuery when eager-loading is set.
	Edges        BotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BotEdges holds the relations/edges for other nodes in the graph.
type BotEdges struct {
	// Exchange holds the value of the exchange edge.
	Exchange *Exchange `json:"exchange,omitempty"`
	// Strategy holds the value of the strategy edge.
	Strategy *Strategy `json:"strategy,omitempty"`
	// Runner holds the value of the runner edge.
	Runner *BotRunner `json:"runner,omitempty"`
	// Trades holds the value of the trades edge.
	Trades []*Trade `json:"trades,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int

	namedTrades map[string][]*Trade
}

// ExchangeOrErr returns the Exchange value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BotEdges) ExchangeOrErr() (*Exchange, error) {
	if e.Exchange != nil {
		return e.Exchange, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: exchange.Label}
	}
	return nil, &NotLoadedError{edge: "exchange"}
}

// StrategyOrErr returns the Strategy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BotEdges) StrategyOrErr() (*Strategy, error) {
	if e.Strategy != nil {
		return e.Strategy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: strategy.Label}
	}
	return nil, &NotLoadedError{edge: "strategy"}
}

// RunnerOrErr returns the Runner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BotEdges) RunnerOrErr() (*BotRunner, error) {
	if e.Runner != nil {
		return e.Runner, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: botrunner.Label}
	}
	return nil, &NotLoadedError{edge: "runner"}
}

// TradesOrErr returns the Trades value or an error if the edge
// was not loaded in eager-loading.
func (e BotEdges) TradesOrErr() ([]*Trade, error) {
	if e.loadedTypes[3] {
		return e.Trades, nil
	}
	return nil, &NotLoadedError{edge: "trades"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bot.FieldConfig:
			values[i] = new([]byte)
		case bot.FieldName, bot.FieldStatus, bot.FieldMode, bot.FieldContainerID, bot.FieldFreqtradeVersion, bot.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case bot.FieldLastSeenAt, bot.FieldCreatedAt, bot.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case bot.FieldID, bot.FieldExchangeID, bot.FieldStrategyID, bot.FieldRunnerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bot fields.
func (_m *Bot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bot.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bot.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case bot.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = enum.BotStatus(value.String)
			}
		case bot.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = enum.BotMode(value.String)
			}
		case bot.FieldContainerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container_id", values[i])
			} else if value.Valid {
				_m.ContainerID = value.String
			}
		case bot.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case bot.FieldFreqtradeVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field freqtrade_version", values[i])
			} else if value.Valid {
				_m.FreqtradeVersion = value.String
			}
		case bot.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case bot.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case bot.FieldExchangeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_id", values[i])
			} else if value != nil {
				_m.ExchangeID = *value
			}
		case bot.FieldStrategyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_id", values[i])
			} else if value != nil {
				_m.StrategyID = *value
			}
		case bot.FieldRunnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field runner_id", values[i])
			} else if value != nil {
				_m.RunnerID = *value
			}
		case bot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bot.
// This includes values selected through modifiers, order, etc.
func (_m *Bot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExchange queries the "exchange" edge of the Bot entity.
func (_m *Bot) QueryExchange() *ExchangeQuery {
	return NewBotClient(_m.config).QueryExchange(_m)
}

// QueryStrategy queries the "strategy" edge of the Bot entity.
func (_m *Bot) QueryStrategy() *StrategyQuery {
	return NewBotClient(_m.config).QueryStrategy(_m)
}

// QueryRunner queries the "runner" edge of the Bot entity.
func (_m *Bot) QueryRunner() *BotRunnerQuery {
	return NewBotClient(_m.config).QueryRunner(_m)
}

// QueryTrades queries the "trades" edge of the Bot entity.
func (_m *Bot) QueryTrades() *TradeQuery {
	return NewBotClient(_m.config).QueryTrades(_m)
}

// Update returns a builder for updating this Bot.
// Note that you need to call Bot.Unwrap() before calling this method if this Bot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Bot) Update() *BotUpdateOne {
	return NewBotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Bot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Bot) Unwrap() *Bot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Bot) String() string {
	var builder strings.Builder
	builder.WriteString("Bot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	builder.WriteString("container_id=")
	builder.WriteString(_m.ContainerID)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("freqtrade_version=")
	builder.WriteString(_m.FreqtradeVersion)
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("exchange_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExchangeID))
	builder.WriteString(", ")
	builder.WriteString("strategy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StrategyID))
	builder.WriteString(", ")
	builder.WriteString("runner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunnerID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedTrades returns the Trades named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Bot) NamedTrades(name string) ([]*Trade, error) {
	if _m.Edges.namedTrades == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTrades[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Bot) appendNamedTrades(name string, edges ...*Trade) {
	if _m.Edges.namedTrades == nil {
		_m.Edges.namedTrades = make(map[string][]*Trade)
	}
	if len(edges) == 0 {
		_m.Edges.namedTrades[name] = []*Trade{}
	} else {
		_m.Edges.namedTrades[name] = append(_m.Edges.namedTrades[name], edges...)
	}
}

// Bots is a parsable slice of Bot.
type Bots []*Bot
