// Code generated by ent, DO NOT EDIT.

package ent

import (
	"anytrade/internal/ent/bot"
	"anytrade/internal/ent/botmetrics"
	"anytrade/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BotMetricsUpdate is the builder for updating BotMetrics entities.
type BotMetricsUpdate struct {
	config
	hooks    []Hook
	mutation *BotMetricsMutation
}

// Where appends a list predicates to the BotMetricsUpdate builder.
func (_u *BotMetricsUpdate) Where(ps ...predicate.BotMetrics) *BotMetricsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBotID sets the "bot_id" field.
func (_u *BotMetricsUpdate) SetBotID(v uuid.UUID) *BotMetricsUpdate {
	_u.mutation.SetBotID(v)
	return _u
}

// SetNillableBotID sets the "bot_id" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableBotID(v *uuid.UUID) *BotMetricsUpdate {
	if v != nil {
		_u.SetBotID(*v)
	}
	return _u
}

// SetProfitClosedCoin sets the "profit_closed_coin" field.
func (_u *BotMetricsUpdate) SetProfitClosedCoin(v float64) *BotMetricsUpdate {
	_u.mutation.ResetProfitClosedCoin()
	_u.mutation.SetProfitClosedCoin(v)
	return _u
}

// SetNillableProfitClosedCoin sets the "profit_closed_coin" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableProfitClosedCoin(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetProfitClosedCoin(*v)
	}
	return _u
}

// AddProfitClosedCoin adds value to the "profit_closed_coin" field.
func (_u *BotMetricsUpdate) AddProfitClosedCoin(v float64) *BotMetricsUpdate {
	_u.mutation.AddProfitClosedCoin(v)
	return _u
}

// ClearProfitClosedCoin clears the value of the "profit_closed_coin" field.
func (_u *BotMetricsUpdate) ClearProfitClosedCoin() *BotMetricsUpdate {
	_u.mutation.ClearProfitClosedCoin()
	return _u
}

// SetProfitClosedPercent sets the "profit_closed_percent" field.
func (_u *BotMetricsUpdate) SetProfitClosedPercent(v float64) *BotMetricsUpdate {
	_u.mutation.ResetProfitClosedPercent()
	_u.mutation.SetProfitClosedPercent(v)
	return _u
}

// SetNillableProfitClosedPercent sets the "profit_closed_percent" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableProfitClosedPercent(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetProfitClosedPercent(*v)
	}
	return _u
}

// AddProfitClosedPercent adds value to the "profit_closed_percent" field.
func (_u *BotMetricsUpdate) AddProfitClosedPercent(v float64) *BotMetricsUpdate {
	_u.mutation.AddProfitClosedPercent(v)
	return _u
}

// ClearProfitClosedPercent clears the value of the "profit_closed_percent" field.
func (_u *BotMetricsUpdate) ClearProfitClosedPercent() *BotMetricsUpdate {
	_u.mutation.ClearProfitClosedPercent()
	return _u
}

// SetProfitAllCoin sets the "profit_all_coin" field.
func (_u *BotMetricsUpdate) SetProfitAllCoin(v float64) *BotMetricsUpdate {
	_u.mutation.ResetProfitAllCoin()
	_u.mutation.SetProfitAllCoin(v)
	return _u
}

// SetNillableProfitAllCoin sets the "profit_all_coin" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableProfitAllCoin(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetProfitAllCoin(*v)
	}
	return _u
}

// AddProfitAllCoin adds value to the "profit_all_coin" field.
func (_u *BotMetricsUpdate) AddProfitAllCoin(v float64) *BotMetricsUpdate {
	_u.mutation.AddProfitAllCoin(v)
	return _u
}

// ClearProfitAllCoin clears the value of the "profit_all_coin" field.
func (_u *BotMetricsUpdate) ClearProfitAllCoin() *BotMetricsUpdate {
	_u.mutation.ClearProfitAllCoin()
	return _u
}

// SetProfitAllPercent sets the "profit_all_percent" field.
func (_u *BotMetricsUpdate) SetProfitAllPercent(v float64) *BotMetricsUpdate {
	_u.mutation.ResetProfitAllPercent()
	_u.mutation.SetProfitAllPercent(v)
	return _u
}

// SetNillableProfitAllPercent sets the "profit_all_percent" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableProfitAllPercent(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetProfitAllPercent(*v)
	}
	return _u
}

// AddProfitAllPercent adds value to the "profit_all_percent" field.
func (_u *BotMetricsUpdate) AddProfitAllPercent(v float64) *BotMetricsUpdate {
	_u.mutation.AddProfitAllPercent(v)
	return _u
}

// ClearProfitAllPercent clears the value of the "profit_all_percent" field.
func (_u *BotMetricsUpdate) ClearProfitAllPercent() *BotMetricsUpdate {
	_u.mutation.ClearProfitAllPercent()
	return _u
}

// SetTradeCount sets the "trade_count" field.
func (_u *BotMetricsUpdate) SetTradeCount(v int) *BotMetricsUpdate {
	_u.mutation.ResetTradeCount()
	_u.mutation.SetTradeCount(v)
	return _u
}

// SetNillableTradeCount sets the "trade_count" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableTradeCount(v *int) *BotMetricsUpdate {
	if v != nil {
		_u.SetTradeCount(*v)
	}
	return _u
}

// AddTradeCount adds value to the "trade_count" field.
func (_u *BotMetricsUpdate) AddTradeCount(v int) *BotMetricsUpdate {
	_u.mutation.AddTradeCount(v)
	return _u
}

// ClearTradeCount clears the value of the "trade_count" field.
func (_u *BotMetricsUpdate) ClearTradeCount() *BotMetricsUpdate {
	_u.mutation.ClearTradeCount()
	return _u
}

// SetClosedTradeCount sets the "closed_trade_count" field.
func (_u *BotMetricsUpdate) SetClosedTradeCount(v int) *BotMetricsUpdate {
	_u.mutation.ResetClosedTradeCount()
	_u.mutation.SetClosedTradeCount(v)
	return _u
}

// SetNillableClosedTradeCount sets the "closed_trade_count" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableClosedTradeCount(v *int) *BotMetricsUpdate {
	if v != nil {
		_u.SetClosedTradeCount(*v)
	}
	return _u
}

// AddClosedTradeCount adds value to the "closed_trade_count" field.
func (_u *BotMetricsUpdate) AddClosedTradeCount(v int) *BotMetricsUpdate {
	_u.mutation.AddClosedTradeCount(v)
	return _u
}

// ClearClosedTradeCount clears the value of the "closed_trade_count" field.
func (_u *BotMetricsUpdate) ClearClosedTradeCount() *BotMetricsUpdate {
	_u.mutation.ClearClosedTradeCount()
	return _u
}

// SetOpenTradeCount sets the "open_trade_count" field.
func (_u *BotMetricsUpdate) SetOpenTradeCount(v int) *BotMetricsUpdate {
	_u.mutation.ResetOpenTradeCount()
	_u.mutation.SetOpenTradeCount(v)
	return _u
}

// SetNillableOpenTradeCount sets the "open_trade_count" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableOpenTradeCount(v *int) *BotMetricsUpdate {
	if v != nil {
		_u.SetOpenTradeCount(*v)
	}
	return _u
}

// AddOpenTradeCount adds value to the "open_trade_count" field.
func (_u *BotMetricsUpdate) AddOpenTradeCount(v int) *BotMetricsUpdate {
	_u.mutation.AddOpenTradeCount(v)
	return _u
}

// ClearOpenTradeCount clears the value of the "open_trade_count" field.
func (_u *BotMetricsUpdate) ClearOpenTradeCount() *BotMetricsUpdate {
	_u.mutation.ClearOpenTradeCount()
	return _u
}

// SetWinningTrades sets the "winning_trades" field.
func (_u *BotMetricsUpdate) SetWinningTrades(v int) *BotMetricsUpdate {
	_u.mutation.ResetWinningTrades()
	_u.mutation.SetWinningTrades(v)
	return _u
}

// SetNillableWinningTrades sets the "winning_trades" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableWinningTrades(v *int) *BotMetricsUpdate {
	if v != nil {
		_u.SetWinningTrades(*v)
	}
	return _u
}

// AddWinningTrades adds value to the "winning_trades" field.
func (_u *BotMetricsUpdate) AddWinningTrades(v int) *BotMetricsUpdate {
	_u.mutation.AddWinningTrades(v)
	return _u
}

// ClearWinningTrades clears the value of the "winning_trades" field.
func (_u *BotMetricsUpdate) ClearWinningTrades() *BotMetricsUpdate {
	_u.mutation.ClearWinningTrades()
	return _u
}

// SetLosingTrades sets the "losing_trades" field.
func (_u *BotMetricsUpdate) SetLosingTrades(v int) *BotMetricsUpdate {
	_u.mutation.ResetLosingTrades()
	_u.mutation.SetLosingTrades(v)
	return _u
}

// SetNillableLosingTrades sets the "losing_trades" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableLosingTrades(v *int) *BotMetricsUpdate {
	if v != nil {
		_u.SetLosingTrades(*v)
	}
	return _u
}

// AddLosingTrades adds value to the "losing_trades" field.
func (_u *BotMetricsUpdate) AddLosingTrades(v int) *BotMetricsUpdate {
	_u.mutation.AddLosingTrades(v)
	return _u
}

// ClearLosingTrades clears the value of the "losing_trades" field.
func (_u *BotMetricsUpdate) ClearLosingTrades() *BotMetricsUpdate {
	_u.mutation.ClearLosingTrades()
	return _u
}

// SetWinrate sets the "winrate" field.
func (_u *BotMetricsUpdate) SetWinrate(v float64) *BotMetricsUpdate {
	_u.mutation.ResetWinrate()
	_u.mutation.SetWinrate(v)
	return _u
}

// SetNillableWinrate sets the "winrate" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableWinrate(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetWinrate(*v)
	}
	return _u
}

// AddWinrate adds value to the "winrate" field.
func (_u *BotMetricsUpdate) AddWinrate(v float64) *BotMetricsUpdate {
	_u.mutation.AddWinrate(v)
	return _u
}

// ClearWinrate clears the value of the "winrate" field.
func (_u *BotMetricsUpdate) ClearWinrate() *BotMetricsUpdate {
	_u.mutation.ClearWinrate()
	return _u
}

// SetExpectancy sets the "expectancy" field.
func (_u *BotMetricsUpdate) SetExpectancy(v float64) *BotMetricsUpdate {
	_u.mutation.ResetExpectancy()
	_u.mutation.SetExpectancy(v)
	return _u
}

// SetNillableExpectancy sets the "expectancy" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableExpectancy(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetExpectancy(*v)
	}
	return _u
}

// AddExpectancy adds value to the "expectancy" field.
func (_u *BotMetricsUpdate) AddExpectancy(v float64) *BotMetricsUpdate {
	_u.mutation.AddExpectancy(v)
	return _u
}

// ClearExpectancy clears the value of the "expectancy" field.
func (_u *BotMetricsUpdate) ClearExpectancy() *BotMetricsUpdate {
	_u.mutation.ClearExpectancy()
	return _u
}

// SetProfitFactor sets the "profit_factor" field.
func (_u *BotMetricsUpdate) SetProfitFactor(v float64) *BotMetricsUpdate {
	_u.mutation.ResetProfitFactor()
	_u.mutation.SetProfitFactor(v)
	return _u
}

// SetNillableProfitFactor sets the "profit_factor" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableProfitFactor(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetProfitFactor(*v)
	}
	return _u
}

// AddProfitFactor adds value to the "profit_factor" field.
func (_u *BotMetricsUpdate) AddProfitFactor(v float64) *BotMetricsUpdate {
	_u.mutation.AddProfitFactor(v)
	return _u
}

// ClearProfitFactor clears the value of the "profit_factor" field.
func (_u *BotMetricsUpdate) ClearProfitFactor() *BotMetricsUpdate {
	_u.mutation.ClearProfitFactor()
	return _u
}

// SetMaxDrawdown sets the "max_drawdown" field.
func (_u *BotMetricsUpdate) SetMaxDrawdown(v float64) *BotMetricsUpdate {
	_u.mutation.ResetMaxDrawdown()
	_u.mutation.SetMaxDrawdown(v)
	return _u
}

// SetNillableMaxDrawdown sets the "max_drawdown" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableMaxDrawdown(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetMaxDrawdown(*v)
	}
	return _u
}

// AddMaxDrawdown adds value to the "max_drawdown" field.
func (_u *BotMetricsUpdate) AddMaxDrawdown(v float64) *BotMetricsUpdate {
	_u.mutation.AddMaxDrawdown(v)
	return _u
}

// ClearMaxDrawdown clears the value of the "max_drawdown" field.
func (_u *BotMetricsUpdate) ClearMaxDrawdown() *BotMetricsUpdate {
	_u.mutation.ClearMaxDrawdown()
	return _u
}

// SetMaxDrawdownAbs sets the "max_drawdown_abs" field.
func (_u *BotMetricsUpdate) SetMaxDrawdownAbs(v float64) *BotMetricsUpdate {
	_u.mutation.ResetMaxDrawdownAbs()
	_u.mutation.SetMaxDrawdownAbs(v)
	return _u
}

// SetNillableMaxDrawdownAbs sets the "max_drawdown_abs" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableMaxDrawdownAbs(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetMaxDrawdownAbs(*v)
	}
	return _u
}

// AddMaxDrawdownAbs adds value to the "max_drawdown_abs" field.
func (_u *BotMetricsUpdate) AddMaxDrawdownAbs(v float64) *BotMetricsUpdate {
	_u.mutation.AddMaxDrawdownAbs(v)
	return _u
}

// ClearMaxDrawdownAbs clears the value of the "max_drawdown_abs" field.
func (_u *BotMetricsUpdate) ClearMaxDrawdownAbs() *BotMetricsUpdate {
	_u.mutation.ClearMaxDrawdownAbs()
	return _u
}

// SetBestPair sets the "best_pair" field.
func (_u *BotMetricsUpdate) SetBestPair(v string) *BotMetricsUpdate {
	_u.mutation.SetBestPair(v)
	return _u
}

// SetNillableBestPair sets the "best_pair" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableBestPair(v *string) *BotMetricsUpdate {
	if v != nil {
		_u.SetBestPair(*v)
	}
	return _u
}

// ClearBestPair clears the value of the "best_pair" field.
func (_u *BotMetricsUpdate) ClearBestPair() *BotMetricsUpdate {
	_u.mutation.ClearBestPair()
	return _u
}

// SetBestRate sets the "best_rate" field.
func (_u *BotMetricsUpdate) SetBestRate(v float64) *BotMetricsUpdate {
	_u.mutation.ResetBestRate()
	_u.mutation.SetBestRate(v)
	return _u
}

// SetNillableBestRate sets the "best_rate" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableBestRate(v *float64) *BotMetricsUpdate {
	if v != nil {
		_u.SetBestRate(*v)
	}
	return _u
}

// AddBestRate adds value to the "best_rate" field.
func (_u *BotMetricsUpdate) AddBestRate(v float64) *BotMetricsUpdate {
	_u.mutation.AddBestRate(v)
	return _u
}

// ClearBestRate clears the value of the "best_rate" field.
func (_u *BotMetricsUpdate) ClearBestRate() *BotMetricsUpdate {
	_u.mutation.ClearBestRate()
	return _u
}

// SetFirstTradeTimestamp sets the "first_trade_timestamp" field.
func (_u *BotMetricsUpdate) SetFirstTradeTimestamp(v time.Time) *BotMetricsUpdate {
	_u.mutation.SetFirstTradeTimestamp(v)
	return _u
}

// SetNillableFirstTradeTimestamp sets the "first_trade_timestamp" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableFirstTradeTimestamp(v *time.Time) *BotMetricsUpdate {
	if v != nil {
		_u.SetFirstTradeTimestamp(*v)
	}
	return _u
}

// ClearFirstTradeTimestamp clears the value of the "first_trade_timestamp" field.
func (_u *BotMetricsUpdate) ClearFirstTradeTimestamp() *BotMetricsUpdate {
	_u.mutation.ClearFirstTradeTimestamp()
	return _u
}

// SetLatestTradeTimestamp sets the "latest_trade_timestamp" field.
func (_u *BotMetricsUpdate) SetLatestTradeTimestamp(v time.Time) *BotMetricsUpdate {
	_u.mutation.SetLatestTradeTimestamp(v)
	return _u
}

// SetNillableLatestTradeTimestamp sets the "latest_trade_timestamp" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableLatestTradeTimestamp(v *time.Time) *BotMetricsUpdate {
	if v != nil {
		_u.SetLatestTradeTimestamp(*v)
	}
	return _u
}

// ClearLatestTradeTimestamp clears the value of the "latest_trade_timestamp" field.
func (_u *BotMetricsUpdate) ClearLatestTradeTimestamp() *BotMetricsUpdate {
	_u.mutation.ClearLatestTradeTimestamp()
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *BotMetricsUpdate) SetFetchedAt(v time.Time) *BotMetricsUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *BotMetricsUpdate) SetNillableFetchedAt(v *time.Time) *BotMetricsUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BotMetricsUpdate) SetUpdatedAt(v time.Time) *BotMetricsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBot sets the "bot" edge to the Bot entity.
func (_u *BotMetricsUpdate) SetBot(v *Bot) *BotMetricsUpdate {
	return _u.SetBotID(v.ID)
}

// Mutation returns the BotMetricsMutation object of the builder.
func (_u *BotMetricsUpdate) Mutation() *BotMetricsMutation {
	return _u.mutation
}

// ClearBot clears the "bot" edge to the Bot entity.
func (_u *BotMetricsUpdate) ClearBot() *BotMetricsUpdate {
	_u.mutation.ClearBot()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BotMetricsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BotMetricsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BotMetricsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BotMetricsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BotMetricsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := botmetrics.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BotMetricsUpdate) check() error {
	if _u.mutation.BotCleared() && len(_u.mutation.BotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BotMetrics.bot"`)
	}
	return nil
}

func (_u *BotMetricsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(botmetrics.Table, botmetrics.Columns, sqlgraph.NewFieldSpec(botmetrics.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfitClosedCoin(); ok {
		_spec.SetField(botmetrics.FieldProfitClosedCoin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitClosedCoin(); ok {
		_spec.AddField(botmetrics.FieldProfitClosedCoin, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitClosedCoinCleared() {
		_spec.ClearField(botmetrics.FieldProfitClosedCoin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitClosedPercent(); ok {
		_spec.SetField(botmetrics.FieldProfitClosedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitClosedPercent(); ok {
		_spec.AddField(botmetrics.FieldProfitClosedPercent, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitClosedPercentCleared() {
		_spec.ClearField(botmetrics.FieldProfitClosedPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitAllCoin(); ok {
		_spec.SetField(botmetrics.FieldProfitAllCoin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitAllCoin(); ok {
		_spec.AddField(botmetrics.FieldProfitAllCoin, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitAllCoinCleared() {
		_spec.ClearField(botmetrics.FieldProfitAllCoin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitAllPercent(); ok {
		_spec.SetField(botmetrics.FieldProfitAllPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitAllPercent(); ok {
		_spec.AddField(botmetrics.FieldProfitAllPercent, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitAllPercentCleared() {
		_spec.ClearField(botmetrics.FieldProfitAllPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TradeCount(); ok {
		_spec.SetField(botmetrics.FieldTradeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTradeCount(); ok {
		_spec.AddField(botmetrics.FieldTradeCount, field.TypeInt, value)
	}
	if _u.mutation.TradeCountCleared() {
		_spec.ClearField(botmetrics.FieldTradeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ClosedTradeCount(); ok {
		_spec.SetField(botmetrics.FieldClosedTradeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClosedTradeCount(); ok {
		_spec.AddField(botmetrics.FieldClosedTradeCount, field.TypeInt, value)
	}
	if _u.mutation.ClosedTradeCountCleared() {
		_spec.ClearField(botmetrics.FieldClosedTradeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OpenTradeCount(); ok {
		_spec.SetField(botmetrics.FieldOpenTradeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenTradeCount(); ok {
		_spec.AddField(botmetrics.FieldOpenTradeCount, field.TypeInt, value)
	}
	if _u.mutation.OpenTradeCountCleared() {
		_spec.ClearField(botmetrics.FieldOpenTradeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WinningTrades(); ok {
		_spec.SetField(botmetrics.FieldWinningTrades, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWinningTrades(); ok {
		_spec.AddField(botmetrics.FieldWinningTrades, field.TypeInt, value)
	}
	if _u.mutation.WinningTradesCleared() {
		_spec.ClearField(botmetrics.FieldWinningTrades, field.TypeInt)
	}
	if value, ok := _u.mutation.LosingTrades(); ok {
		_spec.SetField(botmetrics.FieldLosingTrades, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLosingTrades(); ok {
		_spec.AddField(botmetrics.FieldLosingTrades, field.TypeInt, value)
	}
	if _u.mutation.LosingTradesCleared() {
		_spec.ClearField(botmetrics.FieldLosingTrades, field.TypeInt)
	}
	if value, ok := _u.mutation.Winrate(); ok {
		_spec.SetField(botmetrics.FieldWinrate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWinrate(); ok {
		_spec.AddField(botmetrics.FieldWinrate, field.TypeFloat64, value)
	}
	if _u.mutation.WinrateCleared() {
		_spec.ClearField(botmetrics.FieldWinrate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Expectancy(); ok {
		_spec.SetField(botmetrics.FieldExpectancy, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExpectancy(); ok {
		_spec.AddField(botmetrics.FieldExpectancy, field.TypeFloat64, value)
	}
	if _u.mutation.ExpectancyCleared() {
		_spec.ClearField(botmetrics.FieldExpectancy, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitFactor(); ok {
		_spec.SetField(botmetrics.FieldProfitFactor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitFactor(); ok {
		_spec.AddField(botmetrics.FieldProfitFactor, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitFactorCleared() {
		_spec.ClearField(botmetrics.FieldProfitFactor, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MaxDrawdown(); ok {
		_spec.SetField(botmetrics.FieldMaxDrawdown, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDrawdown(); ok {
		_spec.AddField(botmetrics.FieldMaxDrawdown, field.TypeFloat64, value)
	}
	if _u.mutation.MaxDrawdownCleared() {
		_spec.ClearField(botmetrics.FieldMaxDrawdown, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MaxDrawdownAbs(); ok {
		_spec.SetField(botmetrics.FieldMaxDrawdownAbs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDrawdownAbs(); ok {
		_spec.AddField(botmetrics.FieldMaxDrawdownAbs, field.TypeFloat64, value)
	}
	if _u.mutation.MaxDrawdownAbsCleared() {
		_spec.ClearField(botmetrics.FieldMaxDrawdownAbs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BestPair(); ok {
		_spec.SetField(botmetrics.FieldBestPair, field.TypeString, value)
	}
	if _u.mutation.BestPairCleared() {
		_spec.ClearField(botmetrics.FieldBestPair, field.TypeString)
	}
	if value, ok := _u.mutation.BestRate(); ok {
		_spec.SetField(botmetrics.FieldBestRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBestRate(); ok {
		_spec.AddField(botmetrics.FieldBestRate, field.TypeFloat64, value)
	}
	if _u.mutation.BestRateCleared() {
		_spec.ClearField(botmetrics.FieldBestRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FirstTradeTimestamp(); ok {
		_spec.SetField(botmetrics.FieldFirstTradeTimestamp, field.TypeTime, value)
	}
	if _u.mutation.FirstTradeTimestampCleared() {
		_spec.ClearField(botmetrics.FieldFirstTradeTimestamp, field.TypeTime)
	}
	if value, ok := _u.mutation.LatestTradeTimestamp(); ok {
		_spec.SetField(botmetrics.FieldLatestTradeTimestamp, field.TypeTime, value)
	}
	if _u.mutation.LatestTradeTimestampCleared() {
		_spec.ClearField(botmetrics.FieldLatestTradeTimestamp, field.TypeTime)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(botmetrics.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(botmetrics.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   botmetrics.BotTable,
			Columns: []string{botmetrics.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bot.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   botmetrics.BotTable,
			Columns: []string{botmetrics.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{botmetrics.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BotMetricsUpdateOne is the builder for updating a single BotMetrics entity.
type BotMetricsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BotMetricsMutation
}

// SetBotID sets the "bot_id" field.
func (_u *BotMetricsUpdateOne) SetBotID(v uuid.UUID) *BotMetricsUpdateOne {
	_u.mutation.SetBotID(v)
	return _u
}

// SetNillableBotID sets the "bot_id" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableBotID(v *uuid.UUID) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetBotID(*v)
	}
	return _u
}

// SetProfitClosedCoin sets the "profit_closed_coin" field.
func (_u *BotMetricsUpdateOne) SetProfitClosedCoin(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetProfitClosedCoin()
	_u.mutation.SetProfitClosedCoin(v)
	return _u
}

// SetNillableProfitClosedCoin sets the "profit_closed_coin" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableProfitClosedCoin(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetProfitClosedCoin(*v)
	}
	return _u
}

// AddProfitClosedCoin adds value to the "profit_closed_coin" field.
func (_u *BotMetricsUpdateOne) AddProfitClosedCoin(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddProfitClosedCoin(v)
	return _u
}

// ClearProfitClosedCoin clears the value of the "profit_closed_coin" field.
func (_u *BotMetricsUpdateOne) ClearProfitClosedCoin() *BotMetricsUpdateOne {
	_u.mutation.ClearProfitClosedCoin()
	return _u
}

// SetProfitClosedPercent sets the "profit_closed_percent" field.
func (_u *BotMetricsUpdateOne) SetProfitClosedPercent(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetProfitClosedPercent()
	_u.mutation.SetProfitClosedPercent(v)
	return _u
}

// SetNillableProfitClosedPercent sets the "profit_closed_percent" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableProfitClosedPercent(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetProfitClosedPercent(*v)
	}
	return _u
}

// AddProfitClosedPercent adds value to the "profit_closed_percent" field.
func (_u *BotMetricsUpdateOne) AddProfitClosedPercent(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddProfitClosedPercent(v)
	return _u
}

// ClearProfitClosedPercent clears the value of the "profit_closed_percent" field.
func (_u *BotMetricsUpdateOne) ClearProfitClosedPercent() *BotMetricsUpdateOne {
	_u.mutation.ClearProfitClosedPercent()
	return _u
}

// SetProfitAllCoin sets the "profit_all_coin" field.
func (_u *BotMetricsUpdateOne) SetProfitAllCoin(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetProfitAllCoin()
	_u.mutation.SetProfitAllCoin(v)
	return _u
}

// SetNillableProfitAllCoin sets the "profit_all_coin" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableProfitAllCoin(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetProfitAllCoin(*v)
	}
	return _u
}

// AddProfitAllCoin adds value to the "profit_all_coin" field.
func (_u *BotMetricsUpdateOne) AddProfitAllCoin(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddProfitAllCoin(v)
	return _u
}

// ClearProfitAllCoin clears the value of the "profit_all_coin" field.
func (_u *BotMetricsUpdateOne) ClearProfitAllCoin() *BotMetricsUpdateOne {
	_u.mutation.ClearProfitAllCoin()
	return _u
}

// SetProfitAllPercent sets the "profit_all_percent" field.
func (_u *BotMetricsUpdateOne) SetProfitAllPercent(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetProfitAllPercent()
	_u.mutation.SetProfitAllPercent(v)
	return _u
}

// SetNillableProfitAllPercent sets the "profit_all_percent" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableProfitAllPercent(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetProfitAllPercent(*v)
	}
	return _u
}

// AddProfitAllPercent adds value to the "profit_all_percent" field.
func (_u *BotMetricsUpdateOne) AddProfitAllPercent(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddProfitAllPercent(v)
	return _u
}

// ClearProfitAllPercent clears the value of the "profit_all_percent" field.
func (_u *BotMetricsUpdateOne) ClearProfitAllPercent() *BotMetricsUpdateOne {
	_u.mutation.ClearProfitAllPercent()
	return _u
}

// SetTradeCount sets the "trade_count" field.
func (_u *BotMetricsUpdateOne) SetTradeCount(v int) *BotMetricsUpdateOne {
	_u.mutation.ResetTradeCount()
	_u.mutation.SetTradeCount(v)
	return _u
}

// SetNillableTradeCount sets the "trade_count" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableTradeCount(v *int) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetTradeCount(*v)
	}
	return _u
}

// AddTradeCount adds value to the "trade_count" field.
func (_u *BotMetricsUpdateOne) AddTradeCount(v int) *BotMetricsUpdateOne {
	_u.mutation.AddTradeCount(v)
	return _u
}

// ClearTradeCount clears the value of the "trade_count" field.
func (_u *BotMetricsUpdateOne) ClearTradeCount() *BotMetricsUpdateOne {
	_u.mutation.ClearTradeCount()
	return _u
}

// SetClosedTradeCount sets the "closed_trade_count" field.
func (_u *BotMetricsUpdateOne) SetClosedTradeCount(v int) *BotMetricsUpdateOne {
	_u.mutation.ResetClosedTradeCount()
	_u.mutation.SetClosedTradeCount(v)
	return _u
}

// SetNillableClosedTradeCount sets the "closed_trade_count" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableClosedTradeCount(v *int) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetClosedTradeCount(*v)
	}
	return _u
}

// AddClosedTradeCount adds value to the "closed_trade_count" field.
func (_u *BotMetricsUpdateOne) AddClosedTradeCount(v int) *BotMetricsUpdateOne {
	_u.mutation.AddClosedTradeCount(v)
	return _u
}

// ClearClosedTradeCount clears the value of the "closed_trade_count" field.
func (_u *BotMetricsUpdateOne) ClearClosedTradeCount() *BotMetricsUpdateOne {
	_u.mutation.ClearClosedTradeCount()
	return _u
}

// SetOpenTradeCount sets the "open_trade_count" field.
func (_u *BotMetricsUpdateOne) SetOpenTradeCount(v int) *BotMetricsUpdateOne {
	_u.mutation.ResetOpenTradeCount()
	_u.mutation.SetOpenTradeCount(v)
	return _u
}

// SetNillableOpenTradeCount sets the "open_trade_count" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableOpenTradeCount(v *int) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetOpenTradeCount(*v)
	}
	return _u
}

// AddOpenTradeCount adds value to the "open_trade_count" field.
func (_u *BotMetricsUpdateOne) AddOpenTradeCount(v int) *BotMetricsUpdateOne {
	_u.mutation.AddOpenTradeCount(v)
	return _u
}

// ClearOpenTradeCount clears the value of the "open_trade_count" field.
func (_u *BotMetricsUpdateOne) ClearOpenTradeCount() *BotMetricsUpdateOne {
	_u.mutation.ClearOpenTradeCount()
	return _u
}

// SetWinningTrades sets the "winning_trades" field.
func (_u *BotMetricsUpdateOne) SetWinningTrades(v int) *BotMetricsUpdateOne {
	_u.mutation.ResetWinningTrades()
	_u.mutation.SetWinningTrades(v)
	return _u
}

// SetNillableWinningTrades sets the "winning_trades" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableWinningTrades(v *int) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetWinningTrades(*v)
	}
	return _u
}

// AddWinningTrades adds value to the "winning_trades" field.
func (_u *BotMetricsUpdateOne) AddWinningTrades(v int) *BotMetricsUpdateOne {
	_u.mutation.AddWinningTrades(v)
	return _u
}

// ClearWinningTrades clears the value of the "winning_trades" field.
func (_u *BotMetricsUpdateOne) ClearWinningTrades() *BotMetricsUpdateOne {
	_u.mutation.ClearWinningTrades()
	return _u
}

// SetLosingTrades sets the "losing_trades" field.
func (_u *BotMetricsUpdateOne) SetLosingTrades(v int) *BotMetricsUpdateOne {
	_u.mutation.ResetLosingTrades()
	_u.mutation.SetLosingTrades(v)
	return _u
}

// SetNillableLosingTrades sets the "losing_trades" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableLosingTrades(v *int) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetLosingTrades(*v)
	}
	return _u
}

// AddLosingTrades adds value to the "losing_trades" field.
func (_u *BotMetricsUpdateOne) AddLosingTrades(v int) *BotMetricsUpdateOne {
	_u.mutation.AddLosingTrades(v)
	return _u
}

// ClearLosingTrades clears the value of the "losing_trades" field.
func (_u *BotMetricsUpdateOne) ClearLosingTrades() *BotMetricsUpdateOne {
	_u.mutation.ClearLosingTrades()
	return _u
}

// SetWinrate sets the "winrate" field.
func (_u *BotMetricsUpdateOne) SetWinrate(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetWinrate()
	_u.mutation.SetWinrate(v)
	return _u
}

// SetNillableWinrate sets the "winrate" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableWinrate(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetWinrate(*v)
	}
	return _u
}

// AddWinrate adds value to the "winrate" field.
func (_u *BotMetricsUpdateOne) AddWinrate(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddWinrate(v)
	return _u
}

// ClearWinrate clears the value of the "winrate" field.
func (_u *BotMetricsUpdateOne) ClearWinrate() *BotMetricsUpdateOne {
	_u.mutation.ClearWinrate()
	return _u
}

// SetExpectancy sets the "expectancy" field.
func (_u *BotMetricsUpdateOne) SetExpectancy(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetExpectancy()
	_u.mutation.SetExpectancy(v)
	return _u
}

// SetNillableExpectancy sets the "expectancy" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableExpectancy(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetExpectancy(*v)
	}
	return _u
}

// AddExpectancy adds value to the "expectancy" field.
func (_u *BotMetricsUpdateOne) AddExpectancy(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddExpectancy(v)
	return _u
}

// ClearExpectancy clears the value of the "expectancy" field.
func (_u *BotMetricsUpdateOne) ClearExpectancy() *BotMetricsUpdateOne {
	_u.mutation.ClearExpectancy()
	return _u
}

// SetProfitFactor sets the "profit_factor" field.
func (_u *BotMetricsUpdateOne) SetProfitFactor(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetProfitFactor()
	_u.mutation.SetProfitFactor(v)
	return _u
}

// SetNillableProfitFactor sets the "profit_factor" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableProfitFactor(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetProfitFactor(*v)
	}
	return _u
}

// AddProfitFactor adds value to the "profit_factor" field.
func (_u *BotMetricsUpdateOne) AddProfitFactor(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddProfitFactor(v)
	return _u
}

// ClearProfitFactor clears the value of the "profit_factor" field.
func (_u *BotMetricsUpdateOne) ClearProfitFactor() *BotMetricsUpdateOne {
	_u.mutation.ClearProfitFactor()
	return _u
}

// SetMaxDrawdown sets the "max_drawdown" field.
func (_u *BotMetricsUpdateOne) SetMaxDrawdown(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetMaxDrawdown()
	_u.mutation.SetMaxDrawdown(v)
	return _u
}

// SetNillableMaxDrawdown sets the "max_drawdown" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableMaxDrawdown(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetMaxDrawdown(*v)
	}
	return _u
}

// AddMaxDrawdown adds value to the "max_drawdown" field.
func (_u *BotMetricsUpdateOne) AddMaxDrawdown(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddMaxDrawdown(v)
	return _u
}

// ClearMaxDrawdown clears the value of the "max_drawdown" field.
func (_u *BotMetricsUpdateOne) ClearMaxDrawdown() *BotMetricsUpdateOne {
	_u.mutation.ClearMaxDrawdown()
	return _u
}

// SetMaxDrawdownAbs sets the "max_drawdown_abs" field.
func (_u *BotMetricsUpdateOne) SetMaxDrawdownAbs(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetMaxDrawdownAbs()
	_u.mutation.SetMaxDrawdownAbs(v)
	return _u
}

// SetNillableMaxDrawdownAbs sets the "max_drawdown_abs" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableMaxDrawdownAbs(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetMaxDrawdownAbs(*v)
	}
	return _u
}

// AddMaxDrawdownAbs adds value to the "max_drawdown_abs" field.
func (_u *BotMetricsUpdateOne) AddMaxDrawdownAbs(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddMaxDrawdownAbs(v)
	return _u
}

// ClearMaxDrawdownAbs clears the value of the "max_drawdown_abs" field.
func (_u *BotMetricsUpdateOne) ClearMaxDrawdownAbs() *BotMetricsUpdateOne {
	_u.mutation.ClearMaxDrawdownAbs()
	return _u
}

// SetBestPair sets the "best_pair" field.
func (_u *BotMetricsUpdateOne) SetBestPair(v string) *BotMetricsUpdateOne {
	_u.mutation.SetBestPair(v)
	return _u
}

// SetNillableBestPair sets the "best_pair" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableBestPair(v *string) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetBestPair(*v)
	}
	return _u
}

// ClearBestPair clears the value of the "best_pair" field.
func (_u *BotMetricsUpdateOne) ClearBestPair() *BotMetricsUpdateOne {
	_u.mutation.ClearBestPair()
	return _u
}

// SetBestRate sets the "best_rate" field.
func (_u *BotMetricsUpdateOne) SetBestRate(v float64) *BotMetricsUpdateOne {
	_u.mutation.ResetBestRate()
	_u.mutation.SetBestRate(v)
	return _u
}

// SetNillableBestRate sets the "best_rate" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableBestRate(v *float64) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetBestRate(*v)
	}
	return _u
}

// AddBestRate adds value to the "best_rate" field.
func (_u *BotMetricsUpdateOne) AddBestRate(v float64) *BotMetricsUpdateOne {
	_u.mutation.AddBestRate(v)
	return _u
}

// ClearBestRate clears the value of the "best_rate" field.
func (_u *BotMetricsUpdateOne) ClearBestRate() *BotMetricsUpdateOne {
	_u.mutation.ClearBestRate()
	return _u
}

// SetFirstTradeTimestamp sets the "first_trade_timestamp" field.
func (_u *BotMetricsUpdateOne) SetFirstTradeTimestamp(v time.Time) *BotMetricsUpdateOne {
	_u.mutation.SetFirstTradeTimestamp(v)
	return _u
}

// SetNillableFirstTradeTimestamp sets the "first_trade_timestamp" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableFirstTradeTimestamp(v *time.Time) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetFirstTradeTimestamp(*v)
	}
	return _u
}

// ClearFirstTradeTimestamp clears the value of the "first_trade_timestamp" field.
func (_u *BotMetricsUpdateOne) ClearFirstTradeTimestamp() *BotMetricsUpdateOne {
	_u.mutation.ClearFirstTradeTimestamp()
	return _u
}

// SetLatestTradeTimestamp sets the "latest_trade_timestamp" field.
func (_u *BotMetricsUpdateOne) SetLatestTradeTimestamp(v time.Time) *BotMetricsUpdateOne {
	_u.mutation.SetLatestTradeTimestamp(v)
	return _u
}

// SetNillableLatestTradeTimestamp sets the "latest_trade_timestamp" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableLatestTradeTimestamp(v *time.Time) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetLatestTradeTimestamp(*v)
	}
	return _u
}

// ClearLatestTradeTimestamp clears the value of the "latest_trade_timestamp" field.
func (_u *BotMetricsUpdateOne) ClearLatestTradeTimestamp() *BotMetricsUpdateOne {
	_u.mutation.ClearLatestTradeTimestamp()
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *BotMetricsUpdateOne) SetFetchedAt(v time.Time) *BotMetricsUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *BotMetricsUpdateOne) SetNillableFetchedAt(v *time.Time) *BotMetricsUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BotMetricsUpdateOne) SetUpdatedAt(v time.Time) *BotMetricsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBot sets the "bot" edge to the Bot entity.
func (_u *BotMetricsUpdateOne) SetBot(v *Bot) *BotMetricsUpdateOne {
	return _u.SetBotID(v.ID)
}

// Mutation returns the BotMetricsMutation object of the builder.
func (_u *BotMetricsUpdateOne) Mutation() *BotMetricsMutation {
	return _u.mutation
}

// ClearBot clears the "bot" edge to the Bot entity.
func (_u *BotMetricsUpdateOne) ClearBot() *BotMetricsUpdateOne {
	_u.mutation.ClearBot()
	return _u
}

// Where appends a list predicates to the BotMetricsUpdate builder.
func (_u *BotMetricsUpdateOne) Where(ps ...predicate.BotMetrics) *BotMetricsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BotMetricsUpdateOne) Select(field string, fields ...string) *BotMetricsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BotMetrics entity.
func (_u *BotMetricsUpdateOne) Save(ctx context.Context) (*BotMetrics, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BotMetricsUpdateOne) SaveX(ctx context.Context) *BotMetrics {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BotMetricsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BotMetricsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BotMetricsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := botmetrics.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BotMetricsUpdateOne) check() error {
	if _u.mutation.BotCleared() && len(_u.mutation.BotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BotMetrics.bot"`)
	}
	return nil
}

func (_u *BotMetricsUpdateOne) sqlSave(ctx context.Context) (_node *BotMetrics, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(botmetrics.Table, botmetrics.Columns, sqlgraph.NewFieldSpec(botmetrics.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BotMetrics.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, botmetrics.FieldID)
		for _, f := range fields {
			if !botmetrics.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != botmetrics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProfitClosedCoin(); ok {
		_spec.SetField(botmetrics.FieldProfitClosedCoin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitClosedCoin(); ok {
		_spec.AddField(botmetrics.FieldProfitClosedCoin, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitClosedCoinCleared() {
		_spec.ClearField(botmetrics.FieldProfitClosedCoin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitClosedPercent(); ok {
		_spec.SetField(botmetrics.FieldProfitClosedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitClosedPercent(); ok {
		_spec.AddField(botmetrics.FieldProfitClosedPercent, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitClosedPercentCleared() {
		_spec.ClearField(botmetrics.FieldProfitClosedPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitAllCoin(); ok {
		_spec.SetField(botmetrics.FieldProfitAllCoin, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitAllCoin(); ok {
		_spec.AddField(botmetrics.FieldProfitAllCoin, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitAllCoinCleared() {
		_spec.ClearField(botmetrics.FieldProfitAllCoin, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitAllPercent(); ok {
		_spec.SetField(botmetrics.FieldProfitAllPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitAllPercent(); ok {
		_spec.AddField(botmetrics.FieldProfitAllPercent, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitAllPercentCleared() {
		_spec.ClearField(botmetrics.FieldProfitAllPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TradeCount(); ok {
		_spec.SetField(botmetrics.FieldTradeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTradeCount(); ok {
		_spec.AddField(botmetrics.FieldTradeCount, field.TypeInt, value)
	}
	if _u.mutation.TradeCountCleared() {
		_spec.ClearField(botmetrics.FieldTradeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ClosedTradeCount(); ok {
		_spec.SetField(botmetrics.FieldClosedTradeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClosedTradeCount(); ok {
		_spec.AddField(botmetrics.FieldClosedTradeCount, field.TypeInt, value)
	}
	if _u.mutation.ClosedTradeCountCleared() {
		_spec.ClearField(botmetrics.FieldClosedTradeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OpenTradeCount(); ok {
		_spec.SetField(botmetrics.FieldOpenTradeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenTradeCount(); ok {
		_spec.AddField(botmetrics.FieldOpenTradeCount, field.TypeInt, value)
	}
	if _u.mutation.OpenTradeCountCleared() {
		_spec.ClearField(botmetrics.FieldOpenTradeCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WinningTrades(); ok {
		_spec.SetField(botmetrics.FieldWinningTrades, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWinningTrades(); ok {
		_spec.AddField(botmetrics.FieldWinningTrades, field.TypeInt, value)
	}
	if _u.mutation.WinningTradesCleared() {
		_spec.ClearField(botmetrics.FieldWinningTrades, field.TypeInt)
	}
	if value, ok := _u.mutation.LosingTrades(); ok {
		_spec.SetField(botmetrics.FieldLosingTrades, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLosingTrades(); ok {
		_spec.AddField(botmetrics.FieldLosingTrades, field.TypeInt, value)
	}
	if _u.mutation.LosingTradesCleared() {
		_spec.ClearField(botmetrics.FieldLosingTrades, field.TypeInt)
	}
	if value, ok := _u.mutation.Winrate(); ok {
		_spec.SetField(botmetrics.FieldWinrate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWinrate(); ok {
		_spec.AddField(botmetrics.FieldWinrate, field.TypeFloat64, value)
	}
	if _u.mutation.WinrateCleared() {
		_spec.ClearField(botmetrics.FieldWinrate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Expectancy(); ok {
		_spec.SetField(botmetrics.FieldExpectancy, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExpectancy(); ok {
		_spec.AddField(botmetrics.FieldExpectancy, field.TypeFloat64, value)
	}
	if _u.mutation.ExpectancyCleared() {
		_spec.ClearField(botmetrics.FieldExpectancy, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProfitFactor(); ok {
		_spec.SetField(botmetrics.FieldProfitFactor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfitFactor(); ok {
		_spec.AddField(botmetrics.FieldProfitFactor, field.TypeFloat64, value)
	}
	if _u.mutation.ProfitFactorCleared() {
		_spec.ClearField(botmetrics.FieldProfitFactor, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MaxDrawdown(); ok {
		_spec.SetField(botmetrics.FieldMaxDrawdown, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDrawdown(); ok {
		_spec.AddField(botmetrics.FieldMaxDrawdown, field.TypeFloat64, value)
	}
	if _u.mutation.MaxDrawdownCleared() {
		_spec.ClearField(botmetrics.FieldMaxDrawdown, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MaxDrawdownAbs(); ok {
		_spec.SetField(botmetrics.FieldMaxDrawdownAbs, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDrawdownAbs(); ok {
		_spec.AddField(botmetrics.FieldMaxDrawdownAbs, field.TypeFloat64, value)
	}
	if _u.mutation.MaxDrawdownAbsCleared() {
		_spec.ClearField(botmetrics.FieldMaxDrawdownAbs, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BestPair(); ok {
		_spec.SetField(botmetrics.FieldBestPair, field.TypeString, value)
	}
	if _u.mutation.BestPairCleared() {
		_spec.ClearField(botmetrics.FieldBestPair, field.TypeString)
	}
	if value, ok := _u.mutation.BestRate(); ok {
		_spec.SetField(botmetrics.FieldBestRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBestRate(); ok {
		_spec.AddField(botmetrics.FieldBestRate, field.TypeFloat64, value)
	}
	if _u.mutation.BestRateCleared() {
		_spec.ClearField(botmetrics.FieldBestRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FirstTradeTimestamp(); ok {
		_spec.SetField(botmetrics.FieldFirstTradeTimestamp, field.TypeTime, value)
	}
	if _u.mutation.FirstTradeTimestampCleared() {
		_spec.ClearField(botmetrics.FieldFirstTradeTimestamp, field.TypeTime)
	}
	if value, ok := _u.mutation.LatestTradeTimestamp(); ok {
		_spec.SetField(botmetrics.FieldLatestTradeTimestamp, field.TypeTime, value)
	}
	if _u.mutation.LatestTradeTimestampCleared() {
		_spec.ClearField(botmetrics.FieldLatestTradeTimestamp, field.TypeTime)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(botmetrics.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(botmetrics.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   botmetrics.BotTable,
			Columns: []string{botmetrics.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bot.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   botmetrics.BotTable,
			Columns: []string{botmetrics.BotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BotMetrics{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{botmetrics.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
