// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"volaticloud/internal/ent/botrunner"
	"volaticloud/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BotRunnerDelete is the builder for deleting a BotRunner entity.
type BotRunnerDelete struct {
	config
	hooks    []Hook
	mutation *BotRunnerMutation
}

// Where appends a list predicates to the BotRunnerDelete builder.
func (_d *BotRunnerDelete) Where(ps ...predicate.BotRunner) *BotRunnerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BotRunnerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BotRunnerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BotRunnerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(botrunner.Table, sqlgraph.NewFieldSpec(botrunner.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BotRunnerDeleteOne is the builder for deleting a single BotRunner entity.
type BotRunnerDeleteOne struct {
	_d *BotRunnerDelete
}

// Where appends a list predicates to the BotRunnerDelete builder.
func (_d *BotRunnerDeleteOne) Where(ps ...predicate.BotRunner) *BotRunnerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BotRunnerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{botrunner.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BotRunnerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
