// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"volaticloud/internal/ent/credittransaction"
	"volaticloud/internal/enum"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CreditTransactionCreate is the builder for creating a CreditTransaction entity.
type CreditTransactionCreate struct {
	config
	mutation *CreditTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOwnerID sets the "owner_id" field.
func (_c *CreditTransactionCreate) SetOwnerID(v string) *CreditTransactionCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CreditTransactionCreate) SetAmount(v float64) *CreditTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *CreditTransactionCreate) SetBalanceAfter(v float64) *CreditTransactionCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetType sets the "type" field.
func (_c *CreditTransactionCreate) SetType(v enum.CreditTransactionType) *CreditTransactionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CreditTransactionCreate) SetDescription(v string) *CreditTransactionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CreditTransactionCreate) SetNillableDescription(v *string) *CreditTransactionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetReferenceID sets the "reference_id" field.
func (_c *CreditTransactionCreate) SetReferenceID(v string) *CreditTransactionCreate {
	_c.mutation.SetReferenceID(v)
	return _c
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_c *CreditTransactionCreate) SetNillableReferenceID(v *string) *CreditTransactionCreate {
	if v != nil {
		_c.SetReferenceID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CreditTransactionCreate) SetCreatedAt(v time.Time) *CreditTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CreditTransactionCreate) SetNillableCreatedAt(v *time.Time) *CreditTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CreditTransactionCreate) SetID(v uuid.UUID) *CreditTransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CreditTransactionCreate) SetNillableID(v *uuid.UUID) *CreditTransactionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CreditTransactionMutation object of the builder.
func (_c *CreditTransactionCreate) Mutation() *CreditTransactionMutation {
	return _c.mutation
}

// Save creates the CreditTransaction in the database.
func (_c *CreditTransactionCreate) Save(ctx context.Context) (*CreditTransaction, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CreditTransactionCreate) SaveX(ctx context.Context) *CreditTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CreditTransactionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if credittransaction.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized credittransaction.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := credittransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if credittransaction.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized credittransaction.DefaultID (forgotten import ent/runtime?)")
		}
		v := credittransaction.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CreditTransactionCreate) check() error {
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "CreditTransaction.owner_id"`)}
	}
	if v, ok := _c.mutation.OwnerID(); ok {
		if err := credittransaction.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "CreditTransaction.owner_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CreditTransaction.amount"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "CreditTransaction.balance_after"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "CreditTransaction.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := credittransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "CreditTransaction.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreditTransaction.created_at"`)}
	}
	return nil
}

func (_c *CreditTransactionCreate) sqlSave(ctx context.Context) (*CreditTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CreditTransactionCreate) createSpec() (*CreditTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &CreditTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credittransaction.Table, sqlgraph.NewFieldSpec(credittransaction.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(credittransaction.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(credittransaction.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(credittransaction.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(credittransaction.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(credittransaction.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ReferenceID(); ok {
		_spec.SetField(credittransaction.FieldReferenceID, field.TypeString, value)
		_node.ReferenceID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(credittransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditTransaction.Create().
//		SetOwnerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditTransactionUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditTransactionCreate) OnConflict(opts ...sql.ConflictOption) *CreditTransactionUpsertOne {
	_c.conflict = opts
	return &CreditTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditTransactionCreate) OnConflictColumns(columns ...string) *CreditTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditTransactionUpsertOne{
		create: _c,
	}
}

type (
	// CreditTransactionUpsertOne is the builder for "upsert"-ing
	//  one CreditTransaction node.
	CreditTransactionUpsertOne struct {
		create *CreditTransactionCreate
	}

	// CreditTransactionUpsert is the "OnConflict" setter.
	CreditTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetOwnerID sets the "owner_id" field.
func (u *CreditTransactionUpsert) SetOwnerID(v string) *CreditTransactionUpsert {
	u.Set(credittransaction.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *CreditTransactionUpsert) UpdateOwnerID() *CreditTransactionUpsert {
	u.SetExcluded(credittransaction.FieldOwnerID)
	return u
}

// SetAmount sets the "amount" field.
func (u *CreditTransactionUpsert) SetAmount(v float64) *CreditTransactionUpsert {
	u.Set(credittransaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CreditTransactionUpsert) UpdateAmount() *CreditTransactionUpsert {
	u.SetExcluded(credittransaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CreditTransactionUpsert) AddAmount(v float64) *CreditTransactionUpsert {
	u.Add(credittransaction.FieldAmount, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *CreditTransactionUpsert) SetBalanceAfter(v float64) *CreditTransactionUpsert {
	u.Set(credittransaction.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *CreditTransactionUpsert) UpdateBalanceAfter() *CreditTransactionUpsert {
	u.SetExcluded(credittransaction.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *CreditTransactionUpsert) AddBalanceAfter(v float64) *CreditTransactionUpsert {
	u.Add(credittransaction.FieldBalanceAfter, v)
	return u
}

// SetType sets the "type" field.
func (u *CreditTransactionUpsert) SetType(v enum.CreditTransactionType) *CreditTransactionUpsert {
	u.Set(credittransaction.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CreditTransactionUpsert) UpdateType() *CreditTransactionUpsert {
	u.SetExcluded(credittransaction.FieldType)
	return u
}

// SetDescription sets the "description" field.
func (u *CreditTransactionUpsert) SetDescription(v string) *CreditTransactionUpsert {
	u.Set(credittransaction.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CreditTransactionUpsert) UpdateDescription() *CreditTransactionUpsert {
	u.SetExcluded(credittransaction.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *CreditTransactionUpsert) ClearDescription() *CreditTransactionUpsert {
	u.SetNull(credittransaction.FieldDescription)
	return u
}

// SetReferenceID sets the "reference_id" field.
func (u *CreditTransactionUpsert) SetReferenceID(v string) *CreditTransactionUpsert {
	u.Set(credittransaction.FieldReferenceID, v)
	return u
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *CreditTransactionUpsert) UpdateReferenceID() *CreditTransactionUpsert {
	u.SetExcluded(credittransaction.FieldReferenceID)
	return u
}

// ClearReferenceID clears the value of the "reference_id" field.
func (u *CreditTransactionUpsert) ClearReferenceID() *CreditTransactionUpsert {
	u.SetNull(credittransaction.FieldReferenceID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CreditTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(credittransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreditTransactionUpsertOne) UpdateNewValues() *CreditTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(credittransaction.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(credittransaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreditTransactionUpsertOne) Ignore() *CreditTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditTransactionUpsertOne) DoNothing() *CreditTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditTransactionCreate.OnConflict
// documentation for more info.
func (u *CreditTransactionUpsertOne) Update(set func(*CreditTransactionUpsert)) *CreditTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *CreditTransactionUpsertOne) SetOwnerID(v string) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *CreditTransactionUpsertOne) UpdateOwnerID() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateOwnerID()
	})
}

// SetAmount sets the "amount" field.
func (u *CreditTransactionUpsertOne) SetAmount(v float64) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CreditTransactionUpsertOne) AddAmount(v float64) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CreditTransactionUpsertOne) UpdateAmount() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *CreditTransactionUpsertOne) SetBalanceAfter(v float64) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *CreditTransactionUpsertOne) AddBalanceAfter(v float64) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *CreditTransactionUpsertOne) UpdateBalanceAfter() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetType sets the "type" field.
func (u *CreditTransactionUpsertOne) SetType(v enum.CreditTransactionType) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CreditTransactionUpsertOne) UpdateType() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateType()
	})
}

// SetDescription sets the "description" field.
func (u *CreditTransactionUpsertOne) SetDescription(v string) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CreditTransactionUpsertOne) UpdateDescription() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CreditTransactionUpsertOne) ClearDescription() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.ClearDescription()
	})
}

// SetReferenceID sets the "reference_id" field.
func (u *CreditTransactionUpsertOne) SetReferenceID(v string) *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetReferenceID(v)
	})
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *CreditTransactionUpsertOne) UpdateReferenceID() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateReferenceID()
	})
}

// ClearReferenceID clears the value of the "reference_id" field.
func (u *CreditTransactionUpsertOne) ClearReferenceID() *CreditTransactionUpsertOne {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.ClearReferenceID()
	})
}

// Exec executes the query.
func (u *CreditTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreditTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreditTransactionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CreditTransactionUpsertOne.ID is not supported by MySQL driver. Use CreditTransactionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreditTransactionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreditTransactionCreateBulk is the builder for creating many CreditTransaction entities in bulk.
type CreditTransactionCreateBulk struct {
	config
	err      error
	builders []*CreditTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the CreditTransaction entities in the database.
func (_c *CreditTransactionCreateBulk) Save(ctx context.Context) ([]*CreditTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CreditTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreditTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CreditTransactionCreateBulk) SaveX(ctx context.Context) []*CreditTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CreditTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CreditTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreditTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreditTransactionUpsert) {
//			SetOwnerID(v+v).
//		}).
//		Exec(ctx)
func (_c *CreditTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreditTransactionUpsertBulk {
	_c.conflict = opts
	return &CreditTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreditTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CreditTransactionCreateBulk) OnConflictColumns(columns ...string) *CreditTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CreditTransactionUpsertBulk{
		create: _c,
	}
}

// CreditTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of CreditTransaction nodes.
type CreditTransactionUpsertBulk struct {
	create *CreditTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreditTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(credittransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreditTransactionUpsertBulk) UpdateNewValues() *CreditTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(credittransaction.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(credittransaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreditTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreditTransactionUpsertBulk) Ignore() *CreditTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreditTransactionUpsertBulk) DoNothing() *CreditTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreditTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *CreditTransactionUpsertBulk) Update(set func(*CreditTransactionUpsert)) *CreditTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreditTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *CreditTransactionUpsertBulk) SetOwnerID(v string) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *CreditTransactionUpsertBulk) UpdateOwnerID() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateOwnerID()
	})
}

// SetAmount sets the "amount" field.
func (u *CreditTransactionUpsertBulk) SetAmount(v float64) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CreditTransactionUpsertBulk) AddAmount(v float64) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CreditTransactionUpsertBulk) UpdateAmount() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *CreditTransactionUpsertBulk) SetBalanceAfter(v float64) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *CreditTransactionUpsertBulk) AddBalanceAfter(v float64) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *CreditTransactionUpsertBulk) UpdateBalanceAfter() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetType sets the "type" field.
func (u *CreditTransactionUpsertBulk) SetType(v enum.CreditTransactionType) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *CreditTransactionUpsertBulk) UpdateType() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateType()
	})
}

// SetDescription sets the "description" field.
func (u *CreditTransactionUpsertBulk) SetDescription(v string) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CreditTransactionUpsertBulk) UpdateDescription() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CreditTransactionUpsertBulk) ClearDescription() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.ClearDescription()
	})
}

// SetReferenceID sets the "reference_id" field.
func (u *CreditTransactionUpsertBulk) SetReferenceID(v string) *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.SetReferenceID(v)
	})
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *CreditTransactionUpsertBulk) UpdateReferenceID() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.UpdateReferenceID()
	})
}

// ClearReferenceID clears the value of the "reference_id" field.
func (u *CreditTransactionUpsertBulk) ClearReferenceID() *CreditTransactionUpsertBulk {
	return u.Update(func(s *CreditTransactionUpsert) {
		s.ClearReferenceID()
	})
}

// Exec executes the query.
func (u *CreditTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreditTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreditTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreditTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
