// Code generated by ent, DO NOT EDIT.

package ent

import (
	"anytrade/internal/ent/exchange"
	"anytrade/internal/enum"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Exchange is the model entity for the Exchange schema.
type Exchange struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Exchange name from ExchangeType enum
	Name enum.ExchangeType `json:"name,omitempty"`
	// Use testnet/sandbox
	TestMode bool `json:"test_mode,omitempty"`
	// Exchange-specific settings (non-sensitive)
	Config map[string]interface{} `json:"config,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExchangeQuery when eager-loading is set.
	Edges        ExchangeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExchangeEdges holds the relations/edges for other nodes in the graph.
type ExchangeEdges struct {
	// Bots holds the value of the bots edge.
	Bots []*Bot `json:"bots,omitempty"`
	// Secrets holds the value of the secrets edge.
	Secrets []*ExchangeSecret `json:"secrets,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedBots    map[string][]*Bot
	namedSecrets map[string][]*ExchangeSecret
}

// BotsOrErr returns the Bots value or an error if the edge
// was not loaded in eager-loading.
func (e ExchangeEdges) BotsOrErr() ([]*Bot, error) {
	if e.loadedTypes[0] {
		return e.Bots, nil
	}
	return nil, &NotLoadedError{edge: "bots"}
}

// SecretsOrErr returns the Secrets value or an error if the edge
// was not loaded in eager-loading.
func (e ExchangeEdges) SecretsOrErr() ([]*ExchangeSecret, error) {
	if e.loadedTypes[1] {
		return e.Secrets, nil
	}
	return nil, &NotLoadedError{edge: "secrets"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Exchange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exchange.FieldConfig:
			values[i] = new([]byte)
		case exchange.FieldTestMode:
			values[i] = new(sql.NullBool)
		case exchange.FieldName:
			values[i] = new(sql.NullString)
		case exchange.FieldCreatedAt, exchange.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case exchange.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Exchange fields.
func (_m *Exchange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exchange.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case exchange.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = enum.ExchangeType(value.String)
			}
		case exchange.FieldTestMode:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field test_mode", values[i])
			} else if value.Valid {
				_m.TestMode = value.Bool
			}
		case exchange.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case exchange.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case exchange.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Exchange.
// This includes values selected through modifiers, order, etc.
func (_m *Exchange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBots queries the "bots" edge of the Exchange entity.
func (_m *Exchange) QueryBots() *BotQuery {
	return NewExchangeClient(_m.config).QueryBots(_m)
}

// QuerySecrets queries the "secrets" edge of the Exchange entity.
func (_m *Exchange) QuerySecrets() *ExchangeSecretQuery {
	return NewExchangeClient(_m.config).QuerySecrets(_m)
}

// Update returns a builder for updating this Exchange.
// Note that you need to call Exchange.Unwrap() before calling this method if this Exchange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Exchange) Update() *ExchangeUpdateOne {
	return NewExchangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Exchange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Exchange) Unwrap() *Exchange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Exchange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Exchange) String() string {
	var builder strings.Builder
	builder.WriteString("Exchange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(fmt.Sprintf("%v", _m.Name))
	builder.WriteString(", ")
	builder.WriteString("test_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.TestMode))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedBots returns the Bots named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Exchange) NamedBots(name string) ([]*Bot, error) {
	if _m.Edges.namedBots == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedBots[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Exchange) appendNamedBots(name string, edges ...*Bot) {
	if _m.Edges.namedBots == nil {
		_m.Edges.namedBots = make(map[string][]*Bot)
	}
	if len(edges) == 0 {
		_m.Edges.namedBots[name] = []*Bot{}
	} else {
		_m.Edges.namedBots[name] = append(_m.Edges.namedBots[name], edges...)
	}
}

// NamedSecrets returns the Secrets named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Exchange) NamedSecrets(name string) ([]*ExchangeSecret, error) {
	if _m.Edges.namedSecrets == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSecrets[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Exchange) appendNamedSecrets(name string, edges ...*ExchangeSecret) {
	if _m.Edges.namedSecrets == nil {
		_m.Edges.namedSecrets = make(map[string][]*ExchangeSecret)
	}
	if len(edges) == 0 {
		_m.Edges.namedSecrets[name] = []*ExchangeSecret{}
	} else {
		_m.Edges.namedSecrets[name] = append(_m.Edges.namedSecrets[name], edges...)
	}
}

// Exchanges is a parsable slice of Exchange.
type Exchanges []*Exchange
