// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"volaticloud/internal/enum"

	"github.com/google/uuid"
)

// CreateBacktestInput represents a mutation input for creating backtests.
type CreateBacktestInput struct {
	Status       *enum.TaskStatus
	Result       map[string]interface{}
	ContainerID  *string
	ErrorMessage *string
	Logs         *string
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	CompletedAt  *time.Time
	StartDate    *time.Time
	EndDate      *time.Time
	StrategyID   uuid.UUID
	RunnerID     uuid.UUID
}

// Mutate applies the CreateBacktestInput on the BacktestMutation builder.
func (i *CreateBacktestInput) Mutate(m *BacktestMutation) {
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Result; v != nil {
		m.SetResult(v)
	}
	if v := i.ContainerID; v != nil {
		m.SetContainerID(*v)
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
	if v := i.Logs; v != nil {
		m.SetLogs(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.CompletedAt; v != nil {
		m.SetCompletedAt(*v)
	}
	if v := i.StartDate; v != nil {
		m.SetStartDate(*v)
	}
	if v := i.EndDate; v != nil {
		m.SetEndDate(*v)
	}
	m.SetStrategyID(i.StrategyID)
	m.SetRunnerID(i.RunnerID)
}

// SetInput applies the change-set in the CreateBacktestInput on the BacktestCreate builder.
func (c *BacktestCreate) SetInput(i CreateBacktestInput) *BacktestCreate {
	i.Mutate(c.Mutation())
	return c
}

// CreateBotInput represents a mutation input for creating bots.
type CreateBotInput struct {
	Name             string
	Status           *enum.BotStatus
	Mode             *enum.BotMode
	ContainerID      *string
	Config           map[string]interface{}
	FreqtradeVersion *string
	LastSeenAt       *time.Time
	ErrorMessage     *string
	OwnerID          string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	ExchangeID       uuid.UUID
	StrategyID       uuid.UUID
	RunnerID         uuid.UUID
	TradeIDs         []uuid.UUID
	MetricsID        *uuid.UUID
}

// Mutate applies the CreateBotInput on the BotMutation builder.
func (i *CreateBotInput) Mutate(m *BotMutation) {
	m.SetName(i.Name)
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Mode; v != nil {
		m.SetMode(*v)
	}
	if v := i.ContainerID; v != nil {
		m.SetContainerID(*v)
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.FreqtradeVersion; v != nil {
		m.SetFreqtradeVersion(*v)
	}
	if v := i.LastSeenAt; v != nil {
		m.SetLastSeenAt(*v)
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
	m.SetOwnerID(i.OwnerID)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetExchangeID(i.ExchangeID)
	m.SetStrategyID(i.StrategyID)
	m.SetRunnerID(i.RunnerID)
	if v := i.TradeIDs; len(v) > 0 {
		m.AddTradeIDs(v...)
	}
	if v := i.MetricsID; v != nil {
		m.SetMetricsID(*v)
	}
}

// SetInput applies the change-set in the CreateBotInput on the BotCreate builder.
func (c *BotCreate) SetInput(i CreateBotInput) *BotCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateBotInput represents a mutation input for updating bots.
type UpdateBotInput struct {
	Name              *string
	Status            *enum.BotStatus
	Mode              *enum.BotMode
	ClearContainerID  bool
	ContainerID       *string
	ClearConfig       bool
	Config            map[string]interface{}
	FreqtradeVersion  *string
	ClearLastSeenAt   bool
	LastSeenAt        *time.Time
	ClearErrorMessage bool
	ErrorMessage      *string
	OwnerID           *string
	UpdatedAt         *time.Time
	ExchangeID        *uuid.UUID
	StrategyID        *uuid.UUID
	RunnerID          *uuid.UUID
	ClearTrades       bool
	AddTradeIDs       []uuid.UUID
	RemoveTradeIDs    []uuid.UUID
	ClearMetrics      bool
	MetricsID         *uuid.UUID
}

// Mutate applies the UpdateBotInput on the BotMutation builder.
func (i *UpdateBotInput) Mutate(m *BotMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Mode; v != nil {
		m.SetMode(*v)
	}
	if i.ClearContainerID {
		m.ClearContainerID()
	}
	if v := i.ContainerID; v != nil {
		m.SetContainerID(*v)
	}
	if i.ClearConfig {
		m.ClearConfig()
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.FreqtradeVersion; v != nil {
		m.SetFreqtradeVersion(*v)
	}
	if i.ClearLastSeenAt {
		m.ClearLastSeenAt()
	}
	if v := i.LastSeenAt; v != nil {
		m.SetLastSeenAt(*v)
	}
	if i.ClearErrorMessage {
		m.ClearErrorMessage()
	}
	if v := i.ErrorMessage; v != nil {
		m.SetErrorMessage(*v)
	}
	if v := i.OwnerID; v != nil {
		m.SetOwnerID(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.ExchangeID; v != nil {
		m.SetExchangeID(*v)
	}
	if v := i.StrategyID; v != nil {
		m.SetStrategyID(*v)
	}
	if v := i.RunnerID; v != nil {
		m.SetRunnerID(*v)
	}
	if i.ClearTrades {
		m.ClearTrades()
	}
	if v := i.AddTradeIDs; len(v) > 0 {
		m.AddTradeIDs(v...)
	}
	if v := i.RemoveTradeIDs; len(v) > 0 {
		m.RemoveTradeIDs(v...)
	}
	if i.ClearMetrics {
		m.ClearMetrics()
	}
	if v := i.MetricsID; v != nil {
		m.SetMetricsID(*v)
	}
}

// SetInput applies the change-set in the UpdateBotInput on the BotUpdate builder.
func (c *BotUpdate) SetInput(i UpdateBotInput) *BotUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateBotInput on the BotUpdateOne builder.
func (c *BotUpdateOne) SetInput(i UpdateBotInput) *BotUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateBotMetricsInput represents a mutation input for creating botmetricsslice.
type CreateBotMetricsInput struct {
	ProfitClosedCoin     *float64
	ProfitClosedPercent  *float64
	ProfitAllCoin        *float64
	ProfitAllPercent     *float64
	TradeCount           *int
	ClosedTradeCount     *int
	OpenTradeCount       *int
	WinningTrades        *int
	LosingTrades         *int
	Winrate              *float64
	Expectancy           *float64
	ProfitFactor         *float64
	MaxDrawdown          *float64
	MaxDrawdownAbs       *float64
	BestPair             *string
	BestRate             *float64
	FirstTradeTimestamp  *time.Time
	LatestTradeTimestamp *time.Time
	FetchedAt            *time.Time
	UpdatedAt            *time.Time
	BotID                uuid.UUID
}

// Mutate applies the CreateBotMetricsInput on the BotMetricsMutation builder.
func (i *CreateBotMetricsInput) Mutate(m *BotMetricsMutation) {
	if v := i.ProfitClosedCoin; v != nil {
		m.SetProfitClosedCoin(*v)
	}
	if v := i.ProfitClosedPercent; v != nil {
		m.SetProfitClosedPercent(*v)
	}
	if v := i.ProfitAllCoin; v != nil {
		m.SetProfitAllCoin(*v)
	}
	if v := i.ProfitAllPercent; v != nil {
		m.SetProfitAllPercent(*v)
	}
	if v := i.TradeCount; v != nil {
		m.SetTradeCount(*v)
	}
	if v := i.ClosedTradeCount; v != nil {
		m.SetClosedTradeCount(*v)
	}
	if v := i.OpenTradeCount; v != nil {
		m.SetOpenTradeCount(*v)
	}
	if v := i.WinningTrades; v != nil {
		m.SetWinningTrades(*v)
	}
	if v := i.LosingTrades; v != nil {
		m.SetLosingTrades(*v)
	}
	if v := i.Winrate; v != nil {
		m.SetWinrate(*v)
	}
	if v := i.Expectancy; v != nil {
		m.SetExpectancy(*v)
	}
	if v := i.ProfitFactor; v != nil {
		m.SetProfitFactor(*v)
	}
	if v := i.MaxDrawdown; v != nil {
		m.SetMaxDrawdown(*v)
	}
	if v := i.MaxDrawdownAbs; v != nil {
		m.SetMaxDrawdownAbs(*v)
	}
	if v := i.BestPair; v != nil {
		m.SetBestPair(*v)
	}
	if v := i.BestRate; v != nil {
		m.SetBestRate(*v)
	}
	if v := i.FirstTradeTimestamp; v != nil {
		m.SetFirstTradeTimestamp(*v)
	}
	if v := i.LatestTradeTimestamp; v != nil {
		m.SetLatestTradeTimestamp(*v)
	}
	if v := i.FetchedAt; v != nil {
		m.SetFetchedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetBotID(i.BotID)
}

// SetInput applies the change-set in the CreateBotMetricsInput on the BotMetricsCreate builder.
func (c *BotMetricsCreate) SetInput(i CreateBotMetricsInput) *BotMetricsCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateBotMetricsInput represents a mutation input for updating botmetricsslice.
type UpdateBotMetricsInput struct {
	ClearProfitClosedCoin     bool
	ProfitClosedCoin          *float64
	ClearProfitClosedPercent  bool
	ProfitClosedPercent       *float64
	ClearProfitAllCoin        bool
	ProfitAllCoin             *float64
	ClearProfitAllPercent     bool
	ProfitAllPercent          *float64
	ClearTradeCount           bool
	TradeCount                *int
	ClearClosedTradeCount     bool
	ClosedTradeCount          *int
	ClearOpenTradeCount       bool
	OpenTradeCount            *int
	ClearWinningTrades        bool
	WinningTrades             *int
	ClearLosingTrades         bool
	LosingTrades              *int
	ClearWinrate              bool
	Winrate                   *float64
	ClearExpectancy           bool
	Expectancy                *float64
	ClearProfitFactor         bool
	ProfitFactor              *float64
	ClearMaxDrawdown          bool
	MaxDrawdown               *float64
	ClearMaxDrawdownAbs       bool
	MaxDrawdownAbs            *float64
	ClearBestPair             bool
	BestPair                  *string
	ClearBestRate             bool
	BestRate                  *float64
	ClearFirstTradeTimestamp  bool
	FirstTradeTimestamp       *time.Time
	ClearLatestTradeTimestamp bool
	LatestTradeTimestamp      *time.Time
	FetchedAt                 *time.Time
	UpdatedAt                 *time.Time
	BotID                     *uuid.UUID
}

// Mutate applies the UpdateBotMetricsInput on the BotMetricsMutation builder.
func (i *UpdateBotMetricsInput) Mutate(m *BotMetricsMutation) {
	if i.ClearProfitClosedCoin {
		m.ClearProfitClosedCoin()
	}
	if v := i.ProfitClosedCoin; v != nil {
		m.SetProfitClosedCoin(*v)
	}
	if i.ClearProfitClosedPercent {
		m.ClearProfitClosedPercent()
	}
	if v := i.ProfitClosedPercent; v != nil {
		m.SetProfitClosedPercent(*v)
	}
	if i.ClearProfitAllCoin {
		m.ClearProfitAllCoin()
	}
	if v := i.ProfitAllCoin; v != nil {
		m.SetProfitAllCoin(*v)
	}
	if i.ClearProfitAllPercent {
		m.ClearProfitAllPercent()
	}
	if v := i.ProfitAllPercent; v != nil {
		m.SetProfitAllPercent(*v)
	}
	if i.ClearTradeCount {
		m.ClearTradeCount()
	}
	if v := i.TradeCount; v != nil {
		m.SetTradeCount(*v)
	}
	if i.ClearClosedTradeCount {
		m.ClearClosedTradeCount()
	}
	if v := i.ClosedTradeCount; v != nil {
		m.SetClosedTradeCount(*v)
	}
	if i.ClearOpenTradeCount {
		m.ClearOpenTradeCount()
	}
	if v := i.OpenTradeCount; v != nil {
		m.SetOpenTradeCount(*v)
	}
	if i.ClearWinningTrades {
		m.ClearWinningTrades()
	}
	if v := i.WinningTrades; v != nil {
		m.SetWinningTrades(*v)
	}
	if i.ClearLosingTrades {
		m.ClearLosingTrades()
	}
	if v := i.LosingTrades; v != nil {
		m.SetLosingTrades(*v)
	}
	if i.ClearWinrate {
		m.ClearWinrate()
	}
	if v := i.Winrate; v != nil {
		m.SetWinrate(*v)
	}
	if i.ClearExpectancy {
		m.ClearExpectancy()
	}
	if v := i.Expectancy; v != nil {
		m.SetExpectancy(*v)
	}
	if i.ClearProfitFactor {
		m.ClearProfitFactor()
	}
	if v := i.ProfitFactor; v != nil {
		m.SetProfitFactor(*v)
	}
	if i.ClearMaxDrawdown {
		m.ClearMaxDrawdown()
	}
	if v := i.MaxDrawdown; v != nil {
		m.SetMaxDrawdown(*v)
	}
	if i.ClearMaxDrawdownAbs {
		m.ClearMaxDrawdownAbs()
	}
	if v := i.MaxDrawdownAbs; v != nil {
		m.SetMaxDrawdownAbs(*v)
	}
	if i.ClearBestPair {
		m.ClearBestPair()
	}
	if v := i.BestPair; v != nil {
		m.SetBestPair(*v)
	}
	if i.ClearBestRate {
		m.ClearBestRate()
	}
	if v := i.BestRate; v != nil {
		m.SetBestRate(*v)
	}
	if i.ClearFirstTradeTimestamp {
		m.ClearFirstTradeTimestamp()
	}
	if v := i.FirstTradeTimestamp; v != nil {
		m.SetFirstTradeTimestamp(*v)
	}
	if i.ClearLatestTradeTimestamp {
		m.ClearLatestTradeTimestamp()
	}
	if v := i.LatestTradeTimestamp; v != nil {
		m.SetLatestTradeTimestamp(*v)
	}
	if v := i.FetchedAt; v != nil {
		m.SetFetchedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.BotID; v != nil {
		m.SetBotID(*v)
	}
}

// SetInput applies the change-set in the UpdateBotMetricsInput on the BotMetricsUpdate builder.
func (c *BotMetricsUpdate) SetInput(i UpdateBotMetricsInput) *BotMetricsUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateBotMetricsInput on the BotMetricsUpdateOne builder.
func (c *BotMetricsUpdateOne) SetInput(i UpdateBotMetricsInput) *BotMetricsUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateBotRunnerInput represents a mutation input for creating botrunners.
type CreateBotRunnerInput struct {
	Name                 string
	Type                 *enum.RunnerType
	Config               map[string]interface{}
	DataIsReady          *bool
	DataLastUpdated      *time.Time
	DataDownloadStatus   *enum.DataDownloadStatus
	DataDownloadProgress map[string]interface{}
	DataErrorMessage     *string
	DataDownloadConfig   map[string]interface{}
	OwnerID              string
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
	BotIDs               []uuid.UUID
	BacktestIDs          []uuid.UUID
}

// Mutate applies the CreateBotRunnerInput on the BotRunnerMutation builder.
func (i *CreateBotRunnerInput) Mutate(m *BotRunnerMutation) {
	m.SetName(i.Name)
	if v := i.Type; v != nil {
		m.SetType(*v)
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.DataIsReady; v != nil {
		m.SetDataIsReady(*v)
	}
	if v := i.DataLastUpdated; v != nil {
		m.SetDataLastUpdated(*v)
	}
	if v := i.DataDownloadStatus; v != nil {
		m.SetDataDownloadStatus(*v)
	}
	if v := i.DataDownloadProgress; v != nil {
		m.SetDataDownloadProgress(v)
	}
	if v := i.DataErrorMessage; v != nil {
		m.SetDataErrorMessage(*v)
	}
	if v := i.DataDownloadConfig; v != nil {
		m.SetDataDownloadConfig(v)
	}
	m.SetOwnerID(i.OwnerID)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.BotIDs; len(v) > 0 {
		m.AddBotIDs(v...)
	}
	if v := i.BacktestIDs; len(v) > 0 {
		m.AddBacktestIDs(v...)
	}
}

// SetInput applies the change-set in the CreateBotRunnerInput on the BotRunnerCreate builder.
func (c *BotRunnerCreate) SetInput(i CreateBotRunnerInput) *BotRunnerCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateBotRunnerInput represents a mutation input for updating botrunners.
type UpdateBotRunnerInput struct {
	Name                      *string
	Type                      *enum.RunnerType
	ClearConfig               bool
	Config                    map[string]interface{}
	DataIsReady               *bool
	ClearDataLastUpdated      bool
	DataLastUpdated           *time.Time
	DataDownloadStatus        *enum.DataDownloadStatus
	ClearDataDownloadProgress bool
	DataDownloadProgress      map[string]interface{}
	ClearDataErrorMessage     bool
	DataErrorMessage          *string
	ClearDataDownloadConfig   bool
	DataDownloadConfig        map[string]interface{}
	OwnerID                   *string
	UpdatedAt                 *time.Time
	ClearBots                 bool
	AddBotIDs                 []uuid.UUID
	RemoveBotIDs              []uuid.UUID
	ClearBacktests            bool
	AddBacktestIDs            []uuid.UUID
	RemoveBacktestIDs         []uuid.UUID
}

// Mutate applies the UpdateBotRunnerInput on the BotRunnerMutation builder.
func (i *UpdateBotRunnerInput) Mutate(m *BotRunnerMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Type; v != nil {
		m.SetType(*v)
	}
	if i.ClearConfig {
		m.ClearConfig()
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.DataIsReady; v != nil {
		m.SetDataIsReady(*v)
	}
	if i.ClearDataLastUpdated {
		m.ClearDataLastUpdated()
	}
	if v := i.DataLastUpdated; v != nil {
		m.SetDataLastUpdated(*v)
	}
	if v := i.DataDownloadStatus; v != nil {
		m.SetDataDownloadStatus(*v)
	}
	if i.ClearDataDownloadProgress {
		m.ClearDataDownloadProgress()
	}
	if v := i.DataDownloadProgress; v != nil {
		m.SetDataDownloadProgress(v)
	}
	if i.ClearDataErrorMessage {
		m.ClearDataErrorMessage()
	}
	if v := i.DataErrorMessage; v != nil {
		m.SetDataErrorMessage(*v)
	}
	if i.ClearDataDownloadConfig {
		m.ClearDataDownloadConfig()
	}
	if v := i.DataDownloadConfig; v != nil {
		m.SetDataDownloadConfig(v)
	}
	if v := i.OwnerID; v != nil {
		m.SetOwnerID(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearBots {
		m.ClearBots()
	}
	if v := i.AddBotIDs; len(v) > 0 {
		m.AddBotIDs(v...)
	}
	if v := i.RemoveBotIDs; len(v) > 0 {
		m.RemoveBotIDs(v...)
	}
	if i.ClearBacktests {
		m.ClearBacktests()
	}
	if v := i.AddBacktestIDs; len(v) > 0 {
		m.AddBacktestIDs(v...)
	}
	if v := i.RemoveBacktestIDs; len(v) > 0 {
		m.RemoveBacktestIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateBotRunnerInput on the BotRunnerUpdate builder.
func (c *BotRunnerUpdate) SetInput(i UpdateBotRunnerInput) *BotRunnerUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateBotRunnerInput on the BotRunnerUpdateOne builder.
func (c *BotRunnerUpdateOne) SetInput(i UpdateBotRunnerInput) *BotRunnerUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateExchangeInput represents a mutation input for creating exchanges.
type CreateExchangeInput struct {
	Name      string
	Config    map[string]interface{}
	OwnerID   string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	BotIDs    []uuid.UUID
}

// Mutate applies the CreateExchangeInput on the ExchangeMutation builder.
func (i *CreateExchangeInput) Mutate(m *ExchangeMutation) {
	m.SetName(i.Name)
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	m.SetOwnerID(i.OwnerID)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.BotIDs; len(v) > 0 {
		m.AddBotIDs(v...)
	}
}

// SetInput applies the change-set in the CreateExchangeInput on the ExchangeCreate builder.
func (c *ExchangeCreate) SetInput(i CreateExchangeInput) *ExchangeCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateExchangeInput represents a mutation input for updating exchanges.
type UpdateExchangeInput struct {
	Name         *string
	ClearConfig  bool
	Config       map[string]interface{}
	OwnerID      *string
	UpdatedAt    *time.Time
	ClearBots    bool
	AddBotIDs    []uuid.UUID
	RemoveBotIDs []uuid.UUID
}

// Mutate applies the UpdateExchangeInput on the ExchangeMutation builder.
func (i *UpdateExchangeInput) Mutate(m *ExchangeMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if i.ClearConfig {
		m.ClearConfig()
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.OwnerID; v != nil {
		m.SetOwnerID(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearBots {
		m.ClearBots()
	}
	if v := i.AddBotIDs; len(v) > 0 {
		m.AddBotIDs(v...)
	}
	if v := i.RemoveBotIDs; len(v) > 0 {
		m.RemoveBotIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateExchangeInput on the ExchangeUpdate builder.
func (c *ExchangeUpdate) SetInput(i UpdateExchangeInput) *ExchangeUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateExchangeInput on the ExchangeUpdateOne builder.
func (c *ExchangeUpdateOne) SetInput(i UpdateExchangeInput) *ExchangeUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateStrategyInput represents a mutation input for creating strategies.
type CreateStrategyInput struct {
	Name          string
	Description   *string
	Code          string
	Config        map[string]interface{}
	IsLatest      *bool
	VersionNumber *int
	OwnerID       string
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	BotIDs        []uuid.UUID
	BacktestID    *uuid.UUID
	ChildIDs      []uuid.UUID
	ParentID      *uuid.UUID
}

// Mutate applies the CreateStrategyInput on the StrategyMutation builder.
func (i *CreateStrategyInput) Mutate(m *StrategyMutation) {
	m.SetName(i.Name)
	if v := i.Description; v != nil {
		m.SetDescription(*v)
	}
	m.SetCode(i.Code)
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.IsLatest; v != nil {
		m.SetIsLatest(*v)
	}
	if v := i.VersionNumber; v != nil {
		m.SetVersionNumber(*v)
	}
	m.SetOwnerID(i.OwnerID)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.BotIDs; len(v) > 0 {
		m.AddBotIDs(v...)
	}
	if v := i.BacktestID; v != nil {
		m.SetBacktestID(*v)
	}
	if v := i.ChildIDs; len(v) > 0 {
		m.AddChildIDs(v...)
	}
	if v := i.ParentID; v != nil {
		m.SetParentID(*v)
	}
}

// SetInput applies the change-set in the CreateStrategyInput on the StrategyCreate builder.
func (c *StrategyCreate) SetInput(i CreateStrategyInput) *StrategyCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateStrategyInput represents a mutation input for updating strategies.
type UpdateStrategyInput struct {
	Name             *string
	ClearDescription bool
	Description      *string
	Code             *string
	Config           map[string]interface{}
	IsLatest         *bool
	VersionNumber    *int
	OwnerID          *string
	UpdatedAt        *time.Time
	ClearBots        bool
	AddBotIDs        []uuid.UUID
	RemoveBotIDs     []uuid.UUID
	ClearBacktest    bool
	BacktestID       *uuid.UUID
	ClearChildren    bool
	AddChildIDs      []uuid.UUID
	RemoveChildIDs   []uuid.UUID
	ClearParent      bool
	ParentID         *uuid.UUID
}

// Mutate applies the UpdateStrategyInput on the StrategyMutation builder.
func (i *UpdateStrategyInput) Mutate(m *StrategyMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if i.ClearDescription {
		m.ClearDescription()
	}
	if v := i.Description; v != nil {
		m.SetDescription(*v)
	}
	if v := i.Code; v != nil {
		m.SetCode(*v)
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.IsLatest; v != nil {
		m.SetIsLatest(*v)
	}
	if v := i.VersionNumber; v != nil {
		m.SetVersionNumber(*v)
	}
	if v := i.OwnerID; v != nil {
		m.SetOwnerID(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if i.ClearBots {
		m.ClearBots()
	}
	if v := i.AddBotIDs; len(v) > 0 {
		m.AddBotIDs(v...)
	}
	if v := i.RemoveBotIDs; len(v) > 0 {
		m.RemoveBotIDs(v...)
	}
	if i.ClearBacktest {
		m.ClearBacktest()
	}
	if v := i.BacktestID; v != nil {
		m.SetBacktestID(*v)
	}
	if i.ClearChildren {
		m.ClearChildren()
	}
	if v := i.AddChildIDs; len(v) > 0 {
		m.AddChildIDs(v...)
	}
	if v := i.RemoveChildIDs; len(v) > 0 {
		m.RemoveChildIDs(v...)
	}
	if i.ClearParent {
		m.ClearParent()
	}
	if v := i.ParentID; v != nil {
		m.SetParentID(*v)
	}
}

// SetInput applies the change-set in the UpdateStrategyInput on the StrategyUpdate builder.
func (c *StrategyUpdate) SetInput(i UpdateStrategyInput) *StrategyUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateStrategyInput on the StrategyUpdateOne builder.
func (c *StrategyUpdateOne) SetInput(i UpdateStrategyInput) *StrategyUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateTradeInput represents a mutation input for creating trades.
type CreateTradeInput struct {
	FreqtradeTradeID int
	Pair             string
	IsOpen           *bool
	OpenDate         time.Time
	CloseDate        *time.Time
	OpenRate         float64
	CloseRate        *float64
	Amount           float64
	StakeAmount      float64
	ProfitAbs        *float64
	ProfitRatio      *float64
	SellReason       *string
	StrategyName     *string
	Timeframe        *string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	BotID            uuid.UUID
}

// Mutate applies the CreateTradeInput on the TradeMutation builder.
func (i *CreateTradeInput) Mutate(m *TradeMutation) {
	m.SetFreqtradeTradeID(i.FreqtradeTradeID)
	m.SetPair(i.Pair)
	if v := i.IsOpen; v != nil {
		m.SetIsOpen(*v)
	}
	m.SetOpenDate(i.OpenDate)
	if v := i.CloseDate; v != nil {
		m.SetCloseDate(*v)
	}
	m.SetOpenRate(i.OpenRate)
	if v := i.CloseRate; v != nil {
		m.SetCloseRate(*v)
	}
	m.SetAmount(i.Amount)
	m.SetStakeAmount(i.StakeAmount)
	if v := i.ProfitAbs; v != nil {
		m.SetProfitAbs(*v)
	}
	if v := i.ProfitRatio; v != nil {
		m.SetProfitRatio(*v)
	}
	if v := i.SellReason; v != nil {
		m.SetSellReason(*v)
	}
	if v := i.StrategyName; v != nil {
		m.SetStrategyName(*v)
	}
	if v := i.Timeframe; v != nil {
		m.SetTimeframe(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	m.SetBotID(i.BotID)
}

// SetInput applies the change-set in the CreateTradeInput on the TradeCreate builder.
func (c *TradeCreate) SetInput(i CreateTradeInput) *TradeCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateTradeInput represents a mutation input for updating trades.
type UpdateTradeInput struct {
	FreqtradeTradeID  *int
	Pair              *string
	IsOpen            *bool
	OpenDate          *time.Time
	ClearCloseDate    bool
	CloseDate         *time.Time
	OpenRate          *float64
	ClearCloseRate    bool
	CloseRate         *float64
	Amount            *float64
	StakeAmount       *float64
	ProfitAbs         *float64
	ProfitRatio       *float64
	ClearSellReason   bool
	SellReason        *string
	ClearStrategyName bool
	StrategyName      *string
	ClearTimeframe    bool
	Timeframe         *string
	UpdatedAt         *time.Time
	BotID             *uuid.UUID
}

// Mutate applies the UpdateTradeInput on the TradeMutation builder.
func (i *UpdateTradeInput) Mutate(m *TradeMutation) {
	if v := i.FreqtradeTradeID; v != nil {
		m.SetFreqtradeTradeID(*v)
	}
	if v := i.Pair; v != nil {
		m.SetPair(*v)
	}
	if v := i.IsOpen; v != nil {
		m.SetIsOpen(*v)
	}
	if v := i.OpenDate; v != nil {
		m.SetOpenDate(*v)
	}
	if i.ClearCloseDate {
		m.ClearCloseDate()
	}
	if v := i.CloseDate; v != nil {
		m.SetCloseDate(*v)
	}
	if v := i.OpenRate; v != nil {
		m.SetOpenRate(*v)
	}
	if i.ClearCloseRate {
		m.ClearCloseRate()
	}
	if v := i.CloseRate; v != nil {
		m.SetCloseRate(*v)
	}
	if v := i.Amount; v != nil {
		m.SetAmount(*v)
	}
	if v := i.StakeAmount; v != nil {
		m.SetStakeAmount(*v)
	}
	if v := i.ProfitAbs; v != nil {
		m.SetProfitAbs(*v)
	}
	if v := i.ProfitRatio; v != nil {
		m.SetProfitRatio(*v)
	}
	if i.ClearSellReason {
		m.ClearSellReason()
	}
	if v := i.SellReason; v != nil {
		m.SetSellReason(*v)
	}
	if i.ClearStrategyName {
		m.ClearStrategyName()
	}
	if v := i.StrategyName; v != nil {
		m.SetStrategyName(*v)
	}
	if i.ClearTimeframe {
		m.ClearTimeframe()
	}
	if v := i.Timeframe; v != nil {
		m.SetTimeframe(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
	if v := i.BotID; v != nil {
		m.SetBotID(*v)
	}
}

// SetInput applies the change-set in the UpdateTradeInput on the TradeUpdate builder.
func (c *TradeUpdate) SetInput(i UpdateTradeInput) *TradeUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateTradeInput on the TradeUpdateOne builder.
func (c *TradeUpdateOne) SetInput(i UpdateTradeInput) *TradeUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
