// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"volaticloud/internal/ent/botrunner"
	"volaticloud/internal/ent/predicate"
	"volaticloud/internal/ent/resourceusagesample"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ResourceUsageSampleQuery is the builder for querying ResourceUsageSample entities.
type ResourceUsageSampleQuery struct {
	config
	ctx        *QueryContext
	order      []resourceusagesample.OrderOption
	inters     []Interceptor
	predicates []predicate.ResourceUsageSample
	withRunner *BotRunnerQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*ResourceUsageSample) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResourceUsageSampleQuery builder.
func (_q *ResourceUsageSampleQuery) Where(ps ...predicate.ResourceUsageSample) *ResourceUsageSampleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ResourceUsageSampleQuery) Limit(limit int) *ResourceUsageSampleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ResourceUsageSampleQuery) Offset(offset int) *ResourceUsageSampleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ResourceUsageSampleQuery) Unique(unique bool) *ResourceUsageSampleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ResourceUsageSampleQuery) Order(o ...resourceusagesample.OrderOption) *ResourceUsageSampleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRunner chains the current query on the "runner" edge.
func (_q *ResourceUsageSampleQuery) QueryRunner() *BotRunnerQuery {
	query := (&BotRunnerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resourceusagesample.Table, resourceusagesample.FieldID, selector),
			sqlgraph.To(botrunner.Table, botrunner.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, resourceusagesample.RunnerTable, resourceusagesample.RunnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ResourceUsageSample entity from the query.
// Returns a *NotFoundError when no ResourceUsageSample was found.
func (_q *ResourceUsageSampleQuery) First(ctx context.Context) (*ResourceUsageSample, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resourceusagesample.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) FirstX(ctx context.Context) *ResourceUsageSample {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResourceUsageSample ID from the query.
// Returns a *NotFoundError when no ResourceUsageSample ID was found.
func (_q *ResourceUsageSampleQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resourceusagesample.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ResourceUsageSample entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ResourceUsageSample entity is found.
// Returns a *NotFoundError when no ResourceUsageSample entities are found.
func (_q *ResourceUsageSampleQuery) Only(ctx context.Context) (*ResourceUsageSample, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resourceusagesample.Label}
	default:
		return nil, &NotSingularError{resourceusagesample.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) OnlyX(ctx context.Context) *ResourceUsageSample {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ResourceUsageSample ID in the query.
// Returns a *NotSingularError when more than one ResourceUsageSample ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ResourceUsageSampleQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resourceusagesample.Label}
	default:
		err = &NotSingularError{resourceusagesample.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResourceUsageSamples.
func (_q *ResourceUsageSampleQuery) All(ctx context.Context) ([]*ResourceUsageSample, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ResourceUsageSample, *ResourceUsageSampleQuery]()
	return withInterceptors[[]*ResourceUsageSample](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) AllX(ctx context.Context) []*ResourceUsageSample {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResourceUsageSample IDs.
func (_q *ResourceUsageSampleQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(resourceusagesample.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ResourceUsageSampleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ResourceUsageSampleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ResourceUsageSampleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ResourceUsageSampleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResourceUsageSampleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ResourceUsageSampleQuery) Clone() *ResourceUsageSampleQuery {
	if _q == nil {
		return nil
	}
	return &ResourceUsageSampleQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]resourceusagesample.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ResourceUsageSample{}, _q.predicates...),
		withRunner: _q.withRunner.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRunner tells the query-builder to eager-load the nodes that are connected to
// the "runner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResourceUsageSampleQuery) WithRunner(opts ...func(*BotRunnerQuery)) *ResourceUsageSampleQuery {
	query := (&BotRunnerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRunner = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceType enum.ResourceType `json:"resource_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ResourceUsageSample.Query().
//		GroupBy(resourceusagesample.FieldResourceType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ResourceUsageSampleQuery) GroupBy(field string, fields ...string) *ResourceUsageSampleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResourceUsageSampleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = resourceusagesample.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceType enum.ResourceType `json:"resource_type,omitempty"`
//	}
//
//	client.ResourceUsageSample.Query().
//		Select(resourceusagesample.FieldResourceType).
//		Scan(ctx, &v)
func (_q *ResourceUsageSampleQuery) Select(fields ...string) *ResourceUsageSampleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ResourceUsageSampleSelect{ResourceUsageSampleQuery: _q}
	sbuild.label = resourceusagesample.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResourceUsageSampleSelect configured with the given aggregations.
func (_q *ResourceUsageSampleQuery) Aggregate(fns ...AggregateFunc) *ResourceUsageSampleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ResourceUsageSampleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !resourceusagesample.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ResourceUsageSampleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ResourceUsageSample, error) {
	var (
		nodes       = []*ResourceUsageSample{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withRunner != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ResourceUsageSample).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ResourceUsageSample{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRunner; query != nil {
		if err := _q.loadRunner(ctx, query, nodes, nil,
			func(n *ResourceUsageSample, e *BotRunner) { n.Edges.Runner = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ResourceUsageSampleQuery) loadRunner(ctx context.Context, query *BotRunnerQuery, nodes []*ResourceUsageSample, init func(*ResourceUsageSample), assign func(*ResourceUsageSample, *BotRunner)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ResourceUsageSample)
	for i := range nodes {
		fk := nodes[i].RunnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(botrunner.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "runner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ResourceUsageSampleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ResourceUsageSampleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(resourceusagesample.Table, resourceusagesample.Columns, sqlgraph.NewFieldSpec(resourceusagesample.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceusagesample.FieldID)
		for i := range fields {
			if fields[i] != resourceusagesample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRunner != nil {
			_spec.Node.AddColumnOnce(resourceusagesample.FieldRunnerID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ResourceUsageSampleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(resourceusagesample.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = resourceusagesample.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResourceUsageSampleGroupBy is the group-by builder for ResourceUsageSample entities.
type ResourceUsageSampleGroupBy struct {
	selector
	build *ResourceUsageSampleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ResourceUsageSampleGroupBy) Aggregate(fns ...AggregateFunc) *ResourceUsageSampleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ResourceUsageSampleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResourceUsageSampleQuery, *ResourceUsageSampleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ResourceUsageSampleGroupBy) sqlScan(ctx context.Context, root *ResourceUsageSampleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResourceUsageSampleSelect is the builder for selecting fields of ResourceUsageSample entities.
type ResourceUsageSampleSelect struct {
	*ResourceUsageSampleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ResourceUsageSampleSelect) Aggregate(fns ...AggregateFunc) *ResourceUsageSampleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ResourceUsageSampleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResourceUsageSampleQuery, *ResourceUsageSampleSelect](ctx, _s.ResourceUsageSampleQuery, _s, _s.inters, v)
}

func (_s *ResourceUsageSampleSelect) sqlScan(ctx context.Context, root *ResourceUsageSampleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
