// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"volaticloud/internal/ent/stripesubscription"
	"volaticloud/internal/enum"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// StripeSubscription is the model entity for the StripeSubscription schema.
type StripeSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Organization alias
	OwnerID string `json:"owner_id,omitempty"`
	// Stripe customer ID
	StripeCustomerID string `json:"stripe_customer_id,omitempty"`
	// Stripe subscription ID
	StripeSubscriptionID string `json:"stripe_subscription_id,omitempty"`
	// Stripe price ID for the plan
	StripePriceID string `json:"stripe_price_id,omitempty"`
	// Plan name: starter, pro, enterprise, or custom
	PlanName string `json:"plan_name,omitempty"`
	// Credit amount deposited on each renewal
	MonthlyDeposit float64 `json:"monthly_deposit,omitempty"`
	// Subscription status
	Status enum.StripeSubStatus `json:"status,omitempty"`
	// Feature flags parsed from Stripe product metadata
	Features []string `json:"features,omitempty"`
	// Start of the current billing period
	CurrentPeriodStart time.Time `json:"current_period_start,omitempty"`
	// End of the current billing period
	CurrentPeriodEnd time.Time `json:"current_period_end,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StripeSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stripesubscription.FieldFeatures:
			values[i] = new([]byte)
		case stripesubscription.FieldMonthlyDeposit:
			values[i] = new(sql.NullFloat64)
		case stripesubscription.FieldOwnerID, stripesubscription.FieldStripeCustomerID, stripesubscription.FieldStripeSubscriptionID, stripesubscription.FieldStripePriceID, stripesubscription.FieldPlanName, stripesubscription.FieldStatus:
			values[i] = new(sql.NullString)
		case stripesubscription.FieldCurrentPeriodStart, stripesubscription.FieldCurrentPeriodEnd, stripesubscription.FieldCreatedAt, stripesubscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case stripesubscription.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StripeSubscription fields.
func (_m *StripeSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stripesubscription.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case stripesubscription.FieldOwnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.String
			}
		case stripesubscription.FieldStripeCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_customer_id", values[i])
			} else if value.Valid {
				_m.StripeCustomerID = value.String
			}
		case stripesubscription.FieldStripeSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_subscription_id", values[i])
			} else if value.Valid {
				_m.StripeSubscriptionID = value.String
			}
		case stripesubscription.FieldStripePriceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_price_id", values[i])
			} else if value.Valid {
				_m.StripePriceID = value.String
			}
		case stripesubscription.FieldPlanName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_name", values[i])
			} else if value.Valid {
				_m.PlanName = value.String
			}
		case stripesubscription.FieldMonthlyDeposit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_deposit", values[i])
			} else if value.Valid {
				_m.MonthlyDeposit = value.Float64
			}
		case stripesubscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = enum.StripeSubStatus(value.String)
			}
		case stripesubscription.FieldFeatures:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field features", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Features); err != nil {
					return fmt.Errorf("unmarshal field features: %w", err)
				}
			}
		case stripesubscription.FieldCurrentPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field current_period_start", values[i])
			} else if value.Valid {
				_m.CurrentPeriodStart = value.Time
			}
		case stripesubscription.FieldCurrentPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field current_period_end", values[i])
			} else if value.Valid {
				_m.CurrentPeriodEnd = value.Time
			}
		case stripesubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case stripesubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StripeSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *StripeSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StripeSubscription.
// Note that you need to call StripeSubscription.Unwrap() before calling this method if this StripeSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StripeSubscription) Update() *StripeSubscriptionUpdateOne {
	return NewStripeSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StripeSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StripeSubscription) Unwrap() *StripeSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StripeSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StripeSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("StripeSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(_m.OwnerID)
	builder.WriteString(", ")
	builder.WriteString("stripe_customer_id=")
	builder.WriteString(_m.StripeCustomerID)
	builder.WriteString(", ")
	builder.WriteString("stripe_subscription_id=")
	builder.WriteString(_m.StripeSubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("stripe_price_id=")
	builder.WriteString(_m.StripePriceID)
	builder.WriteString(", ")
	builder.WriteString("plan_name=")
	builder.WriteString(_m.PlanName)
	builder.WriteString(", ")
	builder.WriteString("monthly_deposit=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyDeposit))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("features=")
	builder.WriteString(fmt.Sprintf("%v", _m.Features))
	builder.WriteString(", ")
	builder.WriteString("current_period_start=")
	builder.WriteString(_m.CurrentPeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("current_period_end=")
	builder.WriteString(_m.CurrentPeriodEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StripeSubscriptions is a parsable slice of StripeSubscription.
type StripeSubscriptions []*StripeSubscription
