apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: anytrade-realm
  namespace: keycloak
  labels:
    app: keycloak
    managed-by: github-actions
  annotations:
    deployment.timestamp: "2025-11-13T19:50:00Z"
spec:
  keycloakCRName: anytrade-keycloak
  realm:
    realm: anytrade
    enabled: true
    displayName: "AnyTrade"
    displayNameHtml: "<b>AnyTrade</b> Trading Platform"

    # Login settings
    loginWithEmailAllowed: true
    registrationAllowed: false  # Disable public registration
    registrationEmailAsUsername: true
    rememberMe: true
    verifyEmail: false
    resetPasswordAllowed: true

    # Token settings
    accessTokenLifespan: 300  # 5 minutes
    accessTokenLifespanForImplicitFlow: 900  # 15 minutes
    ssoSessionIdleTimeout: 1800  # 30 minutes
    ssoSessionMaxLifespan: 36000  # 10 hours
    offlineSessionIdleTimeout: 2592000  # 30 days

    # Security settings
    bruteForceProtected: true
    permanentLockout: false
    maxFailureWaitSeconds: 900
    minimumQuickLoginWaitSeconds: 60
    waitIncrementSeconds: 60
    quickLoginCheckMilliSeconds: 1000
    maxDeltaTimeSeconds: 43200
    failureFactor: 5

    # Roles
    roles:
      realm:
        - name: admin
          description: "Administrator with full access"
          composite: false
        - name: trader
          description: "Trader who can manage bots and strategies"
          composite: false
        - name: viewer
          description: "Read-only access to view data"
          composite: false
        - name: user
          description: "Standard user role"
          composite: false

    # Default roles
    defaultRoles:
      - user

    # Clients (OIDC client defined separately)
    clients: []

    # Users (for development - these should be created via Keycloak UI in production)
    users: []

    # Client scopes
    clientScopes:
      - name: roles
        description: "User roles"
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "false"
        protocolMappers:
          - name: realm roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            consentRequired: false
            config:
              multivalued: "true"
              userinfo.token.claim: "true"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: "realm_roles"
              jsonType.label: String

      - name: email
        description: "OpenID Connect built-in scope: email"
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
        protocolMappers:
          - name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: email
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email
              jsonType.label: String

      - name: profile
        description: "OpenID Connect built-in scope: profile"
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
        protocolMappers:
          - name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: username
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: preferred_username
              jsonType.label: String
