/*
Package organization provides organization management functionality.

# Responsibilities

  - Organization creation with dual identifier system (UUID + Alias)
  - Title validation and sanitization
  - Alias generation and validation
  - Keycloak resource lifecycle management
  - Integration with UMA 2.0 authorization
  - Organization enable/disable (soft delete)

# Dual Identifier System

Organizations use a dual identifier system for maximum flexibility:

  - **UUID**: Internal identifier generated by Keycloak Native Organization API.
    Used for database references, authorization checks, and internal operations.
  - **Alias**: Human-readable, URL-friendly identifier (e.g., "acme-trading").
    Used for API endpoints, URLs, and user-facing references.

This design provides stable internal references (UUID) while allowing
human-friendly external references (Alias). Aliases are immutable after
creation to prevent broken links and maintain URL stability.

See ADR-0012 for detailed rationale.

# Architecture

Organization creation flow (mermaid):

	```mermaid
	flowchart TD
	    A[GraphQL Resolver] --> B[organization.Create]
	    B --> C[validateTitle]
	    B --> D[ValidateAlias / GenerateAliasFromTitle]
	    B --> E[AdminClient.CheckOrganizationAliasExists]
	    B --> F[AdminClient.CreateResource]
	    F --> G[Keycloak Native Organization]
	    F --> H[Keycloak Group + Roles]
	    F --> I[UMA Resource]
	    B --> J[AdminClient.ChangeUserRole]
	```

# Keycloak Entity Creation Order

For organizations, entities are created in this order:

 1. Native Keycloak Organization (source of truth, generates UUID)
 2. Keycloak Group with role subgroups (uses alias as group name)
 3. UMA Resource (uses alias as resource name)

The organization UUID is generated by Keycloak's Native Organization API,
while the alias is either provided by the user or auto-generated from the title.

Entity hierarchy (mermaid):

	```mermaid
	flowchart TD
	    subgraph Keycloak
	        A[Native Organization] -->|generates| B[UUID]
	        A -->|uses| C[Alias]
	        D[Group] -->|name| C
	        D --> E[admin role]
	        D --> F[editor role]
	        D --> G[viewer role]
	        H[UMA Resource] -->|name| C
	    end
	```

# Alias System

## Generation

Aliases can be provided explicitly or auto-generated from the organization title:

	// Explicit alias
	response, err := organization.Create(ctx, organization.CreateRequest{
	    Title:  "My Trading Organization",
	    Alias:  "my-trading-org",  // User-provided alias
	    UserID: userCtx.UserID,
	})

	// Auto-generated alias (from title "My Trading Organization" → "my-trading-organization")
	response, err := organization.Create(ctx, organization.CreateRequest{
	    Title:  "My Trading Organization",
	    UserID: userCtx.UserID,  // Alias auto-generated
	})

Auto-generation algorithm (GenerateAliasFromTitle):
  - Convert to lowercase
  - Normalize Unicode (NFD) and strip diacritics (é → e, ü → u)
  - Replace non-alphanumeric characters with hyphens
  - Collapse consecutive hyphens
  - Trim leading/trailing hyphens
  - Truncate to 50 characters (without trailing hyphen)
  - Generate fallback "org-XXXXXXXX" if result is too short

Alias generation flow (mermaid):

	```mermaid
	flowchart LR
	    A[Title: Café Résumé] --> B[lowercase]
	    B --> C[normalize NFD]
	    C --> D[strip diacritics]
	    D --> E[replace non-alphanumeric]
	    E --> F[collapse hyphens]
	    F --> G[trim & truncate]
	    G --> H[Alias: cafe-resume]
	```

## Validation Rules (ValidateAlias)

  - Length: 3-50 characters
  - Characters: lowercase alphanumeric [a-z0-9] and hyphens [-]
  - Cannot start or end with hyphen
  - Cannot contain consecutive hyphens (--)
  - Cannot start with a dot (security: hidden files)
  - Cannot contain path traversal characters (/, \, ., ..)
  - Must be unique across all organizations

## Immutability

Aliases cannot be changed after organization creation. This ensures:
  - URL stability (bookmarks, external links)
  - API endpoint consistency
  - Audit trail integrity

To "change" an alias, users must create a new organization and migrate resources.

# Soft Delete (Disable/Enable)

Organizations support soft delete via disable/enable operations:

	// Disable (soft delete)
	err := adminClient.DisableOrganization(ctx, orgAlias)

	// Re-enable
	err := adminClient.EnableOrganization(ctx, orgAlias)

Disabled organizations:
  - Are hidden from normal queries
  - Cannot be accessed by non-admin users
  - Retain all data and resources for potential re-enablement
  - Can be permanently deleted after a retention period

Organization lifecycle (mermaid):

	```mermaid
	stateDiagram-v2
	    [*] --> Active: Create
	    Active --> Disabled: Disable (soft delete)
	    Disabled --> Active: Enable
	    Disabled --> [*]: Permanent Delete (after retention)
	```

# Rollback Strategy

If role assignment fails after resource creation, the package automatically
rolls back by deleting the created organization resource to prevent orphaned
resources in Keycloak. The Keycloak extension handles cascading cleanup of
all related entities (Native Organization, Group, UMA Resource).

Rollback flow (mermaid):

	```mermaid
	flowchart TD
	    A[Create Organization] --> B{Success?}
	    B -->|Yes| C[Assign Role]
	    C --> D{Success?}
	    D -->|Yes| E[Return Success]
	    D -->|No| F[Delete Organization]
	    F --> G[Return Error]
	    B -->|No| G
	```

# Usage Examples

## Create with auto-generated alias

	response, err := organization.Create(ctx, organization.CreateRequest{
	    Title:  "Acme Trading Corp",
	    UserID: userCtx.UserID,
	})
	// response.Alias = "acme-trading-corp"

## Create with custom alias

	response, err := organization.Create(ctx, organization.CreateRequest{
	    Title:  "Acme Trading Corp",
	    Alias:  "acme",  // Custom short alias
	    UserID: userCtx.UserID,
	})
	// response.Alias = "acme"

## Validate alias before use

	if err := organization.ValidateAlias("my-org"); err != nil {
	    // Handle validation error
	}

## Generate alias from title

	alias := organization.GenerateAliasFromTitle("Café Résumé")
	// alias = "cafe-resume"

# Title Validation Rules

  - Title is required (non-empty after trimming)
  - Title maximum length: 100 characters
  - Control characters (ASCII < 32 or DEL) are rejected for security

# Constants

	MaxTitleLength = 100  // Maximum organization title length
	MinAliasLength = 3    // Minimum alias length
	MaxAliasLength = 50   // Maximum alias length

# Related ADRs

  - ADR-0008: Multi-Tenant Authorization with UMA 2.0
  - ADR-0012: Organization Alias System
*/
package organization
