// Code generated by ent, DO NOT EDIT.

package botmetrics

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the botmetrics type in the database.
	Label = "bot_metrics"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldBotID holds the string denoting the bot_id field in the database.
	FieldBotID = "bot_id"
	// FieldProfitClosedCoin holds the string denoting the profit_closed_coin field in the database.
	FieldProfitClosedCoin = "profit_closed_coin"
	// FieldProfitClosedPercent holds the string denoting the profit_closed_percent field in the database.
	FieldProfitClosedPercent = "profit_closed_percent"
	// FieldProfitAllCoin holds the string denoting the profit_all_coin field in the database.
	FieldProfitAllCoin = "profit_all_coin"
	// FieldProfitAllPercent holds the string denoting the profit_all_percent field in the database.
	FieldProfitAllPercent = "profit_all_percent"
	// FieldTradeCount holds the string denoting the trade_count field in the database.
	FieldTradeCount = "trade_count"
	// FieldClosedTradeCount holds the string denoting the closed_trade_count field in the database.
	FieldClosedTradeCount = "closed_trade_count"
	// FieldOpenTradeCount holds the string denoting the open_trade_count field in the database.
	FieldOpenTradeCount = "open_trade_count"
	// FieldWinningTrades holds the string denoting the winning_trades field in the database.
	FieldWinningTrades = "winning_trades"
	// FieldLosingTrades holds the string denoting the losing_trades field in the database.
	FieldLosingTrades = "losing_trades"
	// FieldWinrate holds the string denoting the winrate field in the database.
	FieldWinrate = "winrate"
	// FieldExpectancy holds the string denoting the expectancy field in the database.
	FieldExpectancy = "expectancy"
	// FieldProfitFactor holds the string denoting the profit_factor field in the database.
	FieldProfitFactor = "profit_factor"
	// FieldMaxDrawdown holds the string denoting the max_drawdown field in the database.
	FieldMaxDrawdown = "max_drawdown"
	// FieldMaxDrawdownAbs holds the string denoting the max_drawdown_abs field in the database.
	FieldMaxDrawdownAbs = "max_drawdown_abs"
	// FieldBestPair holds the string denoting the best_pair field in the database.
	FieldBestPair = "best_pair"
	// FieldBestRate holds the string denoting the best_rate field in the database.
	FieldBestRate = "best_rate"
	// FieldFirstTradeTimestamp holds the string denoting the first_trade_timestamp field in the database.
	FieldFirstTradeTimestamp = "first_trade_timestamp"
	// FieldLatestTradeTimestamp holds the string denoting the latest_trade_timestamp field in the database.
	FieldLatestTradeTimestamp = "latest_trade_timestamp"
	// FieldFetchedAt holds the string denoting the fetched_at field in the database.
	FieldFetchedAt = "fetched_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLastSyncedTradeID holds the string denoting the last_synced_trade_id field in the database.
	FieldLastSyncedTradeID = "last_synced_trade_id"
	// FieldLastKnownMaxTradeID holds the string denoting the last_known_max_trade_id field in the database.
	FieldLastKnownMaxTradeID = "last_known_max_trade_id"
	// FieldLastTradeSyncAt holds the string denoting the last_trade_sync_at field in the database.
	FieldLastTradeSyncAt = "last_trade_sync_at"
	// EdgeBot holds the string denoting the bot edge name in mutations.
	EdgeBot = "bot"
	// Table holds the table name of the botmetrics in the database.
	Table = "bot_metrics"
	// BotTable is the table that holds the bot relation/edge.
	BotTable = "bot_metrics"
	// BotInverseTable is the table name for the Bot entity.
	// It exists in this package in order to avoid circular dependency with the "bot" package.
	BotInverseTable = "bots"
	// BotColumn is the table column denoting the bot relation/edge.
	BotColumn = "bot_id"
)

// Columns holds all SQL columns for botmetrics fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldBotID,
	FieldProfitClosedCoin,
	FieldProfitClosedPercent,
	FieldProfitAllCoin,
	FieldProfitAllPercent,
	FieldTradeCount,
	FieldClosedTradeCount,
	FieldOpenTradeCount,
	FieldWinningTrades,
	FieldLosingTrades,
	FieldWinrate,
	FieldExpectancy,
	FieldProfitFactor,
	FieldMaxDrawdown,
	FieldMaxDrawdownAbs,
	FieldBestPair,
	FieldBestRate,
	FieldFirstTradeTimestamp,
	FieldLatestTradeTimestamp,
	FieldFetchedAt,
	FieldUpdatedAt,
	FieldLastSyncedTradeID,
	FieldLastKnownMaxTradeID,
	FieldLastTradeSyncAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "volaticloud/internal/ent/runtime"
var (
	Interceptors [1]ent.Interceptor
	// DefaultFetchedAt holds the default value on creation for the "fetched_at" field.
	DefaultFetchedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultLastSyncedTradeID holds the default value on creation for the "last_synced_trade_id" field.
	DefaultLastSyncedTradeID int
	// DefaultLastKnownMaxTradeID holds the default value on creation for the "last_known_max_trade_id" field.
	DefaultLastKnownMaxTradeID int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BotMetrics queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByBotID orders the results by the bot_id field.
func ByBotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBotID, opts...).ToFunc()
}

// ByProfitClosedCoin orders the results by the profit_closed_coin field.
func ByProfitClosedCoin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfitClosedCoin, opts...).ToFunc()
}

// ByProfitClosedPercent orders the results by the profit_closed_percent field.
func ByProfitClosedPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfitClosedPercent, opts...).ToFunc()
}

// ByProfitAllCoin orders the results by the profit_all_coin field.
func ByProfitAllCoin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfitAllCoin, opts...).ToFunc()
}

// ByProfitAllPercent orders the results by the profit_all_percent field.
func ByProfitAllPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfitAllPercent, opts...).ToFunc()
}

// ByTradeCount orders the results by the trade_count field.
func ByTradeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradeCount, opts...).ToFunc()
}

// ByClosedTradeCount orders the results by the closed_trade_count field.
func ByClosedTradeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedTradeCount, opts...).ToFunc()
}

// ByOpenTradeCount orders the results by the open_trade_count field.
func ByOpenTradeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenTradeCount, opts...).ToFunc()
}

// ByWinningTrades orders the results by the winning_trades field.
func ByWinningTrades(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWinningTrades, opts...).ToFunc()
}

// ByLosingTrades orders the results by the losing_trades field.
func ByLosingTrades(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLosingTrades, opts...).ToFunc()
}

// ByWinrate orders the results by the winrate field.
func ByWinrate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWinrate, opts...).ToFunc()
}

// ByExpectancy orders the results by the expectancy field.
func ByExpectancy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectancy, opts...).ToFunc()
}

// ByProfitFactor orders the results by the profit_factor field.
func ByProfitFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfitFactor, opts...).ToFunc()
}

// ByMaxDrawdown orders the results by the max_drawdown field.
func ByMaxDrawdown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxDrawdown, opts...).ToFunc()
}

// ByMaxDrawdownAbs orders the results by the max_drawdown_abs field.
func ByMaxDrawdownAbs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxDrawdownAbs, opts...).ToFunc()
}

// ByBestPair orders the results by the best_pair field.
func ByBestPair(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBestPair, opts...).ToFunc()
}

// ByBestRate orders the results by the best_rate field.
func ByBestRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBestRate, opts...).ToFunc()
}

// ByFirstTradeTimestamp orders the results by the first_trade_timestamp field.
func ByFirstTradeTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstTradeTimestamp, opts...).ToFunc()
}

// ByLatestTradeTimestamp orders the results by the latest_trade_timestamp field.
func ByLatestTradeTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestTradeTimestamp, opts...).ToFunc()
}

// ByFetchedAt orders the results by the fetched_at field.
func ByFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFetchedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLastSyncedTradeID orders the results by the last_synced_trade_id field.
func ByLastSyncedTradeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedTradeID, opts...).ToFunc()
}

// ByLastKnownMaxTradeID orders the results by the last_known_max_trade_id field.
func ByLastKnownMaxTradeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastKnownMaxTradeID, opts...).ToFunc()
}

// ByLastTradeSyncAt orders the results by the last_trade_sync_at field.
func ByLastTradeSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTradeSyncAt, opts...).ToFunc()
}

// ByBotField orders the results by bot field.
func ByBotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBotStep(), sql.OrderByField(field, opts...))
	}
}
func newBotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, BotTable, BotColumn),
	)
}
