/*
Freqtrade API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freqtrade

import (
	"encoding/json"
	"fmt"
)

// SignalDirection the model 'SignalDirection'
type SignalDirection string

// List of SignalDirection
const (
	SIGNALDIRECTION_LONG SignalDirection = "long"
	SIGNALDIRECTION_SHORT SignalDirection = "short"
)

// All allowed values of SignalDirection enum
var AllowedSignalDirectionEnumValues = []SignalDirection{
	"long",
	"short",
}

func (v *SignalDirection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SignalDirection(value)
	for _, existing := range AllowedSignalDirectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SignalDirection", value)
}

// NewSignalDirectionFromValue returns a pointer to a valid SignalDirection
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSignalDirectionFromValue(v string) (*SignalDirection, error) {
	ev := SignalDirection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SignalDirection: valid values are %v", v, AllowedSignalDirectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SignalDirection) IsValid() bool {
	for _, existing := range AllowedSignalDirectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SignalDirection value
func (v SignalDirection) Ptr() *SignalDirection {
	return &v
}

type NullableSignalDirection struct {
	value *SignalDirection
	isSet bool
}

func (v NullableSignalDirection) Get() *SignalDirection {
	return v.value
}

func (v *NullableSignalDirection) Set(val *SignalDirection) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalDirection) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalDirection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalDirection(val *SignalDirection) *NullableSignalDirection {
	return &NullableSignalDirection{value: val, isSet: true}
}

func (v NullableSignalDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalDirection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

