/*
Freqtrade API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freqtrade

import (
	"encoding/json"
)

// checks if the DeleteLockRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteLockRequest{}

// DeleteLockRequest struct for DeleteLockRequest
type DeleteLockRequest struct {
	Pair NullableString `json:"pair,omitempty"`
	Lockid NullableInt64 `json:"lockid,omitempty"`
}

// NewDeleteLockRequest instantiates a new DeleteLockRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteLockRequest() *DeleteLockRequest {
	this := DeleteLockRequest{}
	return &this
}

// NewDeleteLockRequestWithDefaults instantiates a new DeleteLockRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteLockRequestWithDefaults() *DeleteLockRequest {
	this := DeleteLockRequest{}
	return &this
}

// GetPair returns the Pair field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteLockRequest) GetPair() string {
	if o == nil || IsNil(o.Pair.Get()) {
		var ret string
		return ret
	}
	return *o.Pair.Get()
}

// GetPairOk returns a tuple with the Pair field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteLockRequest) GetPairOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pair.Get(), o.Pair.IsSet()
}

// HasPair returns a boolean if a field has been set.
func (o *DeleteLockRequest) HasPair() bool {
	if o != nil && o.Pair.IsSet() {
		return true
	}

	return false
}

// SetPair gets a reference to the given NullableString and assigns it to the Pair field.
func (o *DeleteLockRequest) SetPair(v string) {
	o.Pair.Set(&v)
}
// SetPairNil sets the value for Pair to be an explicit nil
func (o *DeleteLockRequest) SetPairNil() {
	o.Pair.Set(nil)
}

// UnsetPair ensures that no value is present for Pair, not even an explicit nil
func (o *DeleteLockRequest) UnsetPair() {
	o.Pair.Unset()
}

// GetLockid returns the Lockid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeleteLockRequest) GetLockid() int64 {
	if o == nil || IsNil(o.Lockid.Get()) {
		var ret int64
		return ret
	}
	return *o.Lockid.Get()
}

// GetLockidOk returns a tuple with the Lockid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeleteLockRequest) GetLockidOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lockid.Get(), o.Lockid.IsSet()
}

// HasLockid returns a boolean if a field has been set.
func (o *DeleteLockRequest) HasLockid() bool {
	if o != nil && o.Lockid.IsSet() {
		return true
	}

	return false
}

// SetLockid gets a reference to the given NullableInt64 and assigns it to the Lockid field.
func (o *DeleteLockRequest) SetLockid(v int64) {
	o.Lockid.Set(&v)
}
// SetLockidNil sets the value for Lockid to be an explicit nil
func (o *DeleteLockRequest) SetLockidNil() {
	o.Lockid.Set(nil)
}

// UnsetLockid ensures that no value is present for Lockid, not even an explicit nil
func (o *DeleteLockRequest) UnsetLockid() {
	o.Lockid.Unset()
}

func (o DeleteLockRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteLockRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Pair.IsSet() {
		toSerialize["pair"] = o.Pair.Get()
	}
	if o.Lockid.IsSet() {
		toSerialize["lockid"] = o.Lockid.Get()
	}
	return toSerialize, nil
}

type NullableDeleteLockRequest struct {
	value *DeleteLockRequest
	isSet bool
}

func (v NullableDeleteLockRequest) Get() *DeleteLockRequest {
	return v.value
}

func (v *NullableDeleteLockRequest) Set(val *DeleteLockRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteLockRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteLockRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteLockRequest(val *DeleteLockRequest) *NullableDeleteLockRequest {
	return &NullableDeleteLockRequest{value: val, isSet: true}
}

func (v NullableDeleteLockRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteLockRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


