/*
Freqtrade API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freqtrade

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MixTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MixTag{}

// MixTag struct for MixTag
type MixTag struct {
	ProfitRatio float32 `json:"profit_ratio"`
	ProfitPct float32 `json:"profit_pct"`
	ProfitAbs float32 `json:"profit_abs"`
	Count int64 `json:"count"`
	MixTag string `json:"mix_tag"`
}

type _MixTag MixTag

// NewMixTag instantiates a new MixTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMixTag(profitRatio float32, profitPct float32, profitAbs float32, count int64, mixTag string) *MixTag {
	this := MixTag{}
	this.ProfitRatio = profitRatio
	this.ProfitPct = profitPct
	this.ProfitAbs = profitAbs
	this.Count = count
	this.MixTag = mixTag
	return &this
}

// NewMixTagWithDefaults instantiates a new MixTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMixTagWithDefaults() *MixTag {
	this := MixTag{}
	return &this
}

// GetProfitRatio returns the ProfitRatio field value
func (o *MixTag) GetProfitRatio() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProfitRatio
}

// GetProfitRatioOk returns a tuple with the ProfitRatio field value
// and a boolean to check if the value has been set.
func (o *MixTag) GetProfitRatioOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfitRatio, true
}

// SetProfitRatio sets field value
func (o *MixTag) SetProfitRatio(v float32) {
	o.ProfitRatio = v
}

// GetProfitPct returns the ProfitPct field value
func (o *MixTag) GetProfitPct() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProfitPct
}

// GetProfitPctOk returns a tuple with the ProfitPct field value
// and a boolean to check if the value has been set.
func (o *MixTag) GetProfitPctOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfitPct, true
}

// SetProfitPct sets field value
func (o *MixTag) SetProfitPct(v float32) {
	o.ProfitPct = v
}

// GetProfitAbs returns the ProfitAbs field value
func (o *MixTag) GetProfitAbs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProfitAbs
}

// GetProfitAbsOk returns a tuple with the ProfitAbs field value
// and a boolean to check if the value has been set.
func (o *MixTag) GetProfitAbsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfitAbs, true
}

// SetProfitAbs sets field value
func (o *MixTag) SetProfitAbs(v float32) {
	o.ProfitAbs = v
}

// GetCount returns the Count field value
func (o *MixTag) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *MixTag) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *MixTag) SetCount(v int64) {
	o.Count = v
}

// GetMixTag returns the MixTag field value
func (o *MixTag) GetMixTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MixTag
}

// GetMixTagOk returns a tuple with the MixTag field value
// and a boolean to check if the value has been set.
func (o *MixTag) GetMixTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MixTag, true
}

// SetMixTag sets field value
func (o *MixTag) SetMixTag(v string) {
	o.MixTag = v
}

func (o MixTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MixTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["profit_ratio"] = o.ProfitRatio
	toSerialize["profit_pct"] = o.ProfitPct
	toSerialize["profit_abs"] = o.ProfitAbs
	toSerialize["count"] = o.Count
	toSerialize["mix_tag"] = o.MixTag
	return toSerialize, nil
}

func (o *MixTag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"profit_ratio",
		"profit_pct",
		"profit_abs",
		"count",
		"mix_tag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMixTag := _MixTag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMixTag)

	if err != nil {
		return err
	}

	*o = MixTag(varMixTag)

	return err
}

type NullableMixTag struct {
	value *MixTag
	isSet bool
}

func (v NullableMixTag) Get() *MixTag {
	return v.value
}

func (v *NullableMixTag) Set(val *MixTag) {
	v.value = val
	v.isSet = true
}

func (v NullableMixTag) IsSet() bool {
	return v.isSet
}

func (v *NullableMixTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMixTag(val *MixTag) *NullableMixTag {
	return &NullableMixTag{value: val, isSet: true}
}

func (v NullableMixTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMixTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


