/*
Freqtrade API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freqtrade

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProfitAll type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfitAll{}

// ProfitAll struct for ProfitAll
type ProfitAll struct {
	All   Profit         `json:"all"`
	Long  NullableProfit `json:"long,omitempty"`
	Short NullableProfit `json:"short,omitempty"`
}

type _ProfitAll ProfitAll

// NewProfitAll instantiates a new ProfitAll object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfitAll(all Profit) *ProfitAll {
	this := ProfitAll{}
	this.All = all
	return &this
}

// NewProfitAllWithDefaults instantiates a new ProfitAll object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfitAllWithDefaults() *ProfitAll {
	this := ProfitAll{}
	return &this
}

// GetAll returns the All field value
func (o *ProfitAll) GetAll() Profit {
	if o == nil {
		var ret Profit
		return ret
	}

	return o.All
}

// GetAllOk returns a tuple with the All field value
// and a boolean to check if the value has been set.
func (o *ProfitAll) GetAllOk() (*Profit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.All, true
}

// SetAll sets field value
func (o *ProfitAll) SetAll(v Profit) {
	o.All = v
}

// GetLong returns the Long field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProfitAll) GetLong() Profit {
	if o == nil || IsNil(o.Long.Get()) {
		var ret Profit
		return ret
	}
	return *o.Long.Get()
}

// GetLongOk returns a tuple with the Long field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProfitAll) GetLongOk() (*Profit, bool) {
	if o == nil {
		return nil, false
	}
	return o.Long.Get(), o.Long.IsSet()
}

// HasLong returns a boolean if a field has been set.
func (o *ProfitAll) HasLong() bool {
	if o != nil && o.Long.IsSet() {
		return true
	}

	return false
}

// SetLong gets a reference to the given NullableProfit and assigns it to the Long field.
func (o *ProfitAll) SetLong(v Profit) {
	o.Long.Set(&v)
}

// SetLongNil sets the value for Long to be an explicit nil
func (o *ProfitAll) SetLongNil() {
	o.Long.Set(nil)
}

// UnsetLong ensures that no value is present for Long, not even an explicit nil
func (o *ProfitAll) UnsetLong() {
	o.Long.Unset()
}

// GetShort returns the Short field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProfitAll) GetShort() Profit {
	if o == nil || IsNil(o.Short.Get()) {
		var ret Profit
		return ret
	}
	return *o.Short.Get()
}

// GetShortOk returns a tuple with the Short field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProfitAll) GetShortOk() (*Profit, bool) {
	if o == nil {
		return nil, false
	}
	return o.Short.Get(), o.Short.IsSet()
}

// HasShort returns a boolean if a field has been set.
func (o *ProfitAll) HasShort() bool {
	if o != nil && o.Short.IsSet() {
		return true
	}

	return false
}

// SetShort gets a reference to the given NullableProfit and assigns it to the Short field.
func (o *ProfitAll) SetShort(v Profit) {
	o.Short.Set(&v)
}

// SetShortNil sets the value for Short to be an explicit nil
func (o *ProfitAll) SetShortNil() {
	o.Short.Set(nil)
}

// UnsetShort ensures that no value is present for Short, not even an explicit nil
func (o *ProfitAll) UnsetShort() {
	o.Short.Unset()
}

func (o ProfitAll) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfitAll) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["all"] = o.All
	if o.Long.IsSet() {
		toSerialize["long"] = o.Long.Get()
	}
	if o.Short.IsSet() {
		toSerialize["short"] = o.Short.Get()
	}
	return toSerialize, nil
}

func (o *ProfitAll) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"all",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfitAll := _ProfitAll{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfitAll)

	if err != nil {
		return err
	}

	*o = ProfitAll(varProfitAll)

	return err
}

type NullableProfitAll struct {
	value *ProfitAll
	isSet bool
}

func (v NullableProfitAll) Get() *ProfitAll {
	return v.value
}

func (v *NullableProfitAll) Set(val *ProfitAll) {
	v.value = val
	v.isSet = true
}

func (v NullableProfitAll) IsSet() bool {
	return v.isSet
}

func (v *NullableProfitAll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfitAll(val *ProfitAll) *NullableProfitAll {
	return &NullableProfitAll{value: val, isSet: true}
}

func (v NullableProfitAll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfitAll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
