/*
Freqtrade API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freqtrade

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Locks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Locks{}

// Locks struct for Locks
type Locks struct {
	LockCount int64 `json:"lock_count"`
	Locks []LockModel `json:"locks"`
}

type _Locks Locks

// NewLocks instantiates a new Locks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocks(lockCount int64, locks []LockModel) *Locks {
	this := Locks{}
	this.LockCount = lockCount
	this.Locks = locks
	return &this
}

// NewLocksWithDefaults instantiates a new Locks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocksWithDefaults() *Locks {
	this := Locks{}
	return &this
}

// GetLockCount returns the LockCount field value
func (o *Locks) GetLockCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LockCount
}

// GetLockCountOk returns a tuple with the LockCount field value
// and a boolean to check if the value has been set.
func (o *Locks) GetLockCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LockCount, true
}

// SetLockCount sets field value
func (o *Locks) SetLockCount(v int64) {
	o.LockCount = v
}

// GetLocks returns the Locks field value
func (o *Locks) GetLocks() []LockModel {
	if o == nil {
		var ret []LockModel
		return ret
	}

	return o.Locks
}

// GetLocksOk returns a tuple with the Locks field value
// and a boolean to check if the value has been set.
func (o *Locks) GetLocksOk() ([]LockModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locks, true
}

// SetLocks sets field value
func (o *Locks) SetLocks(v []LockModel) {
	o.Locks = v
}

func (o Locks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Locks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lock_count"] = o.LockCount
	toSerialize["locks"] = o.Locks
	return toSerialize, nil
}

func (o *Locks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lock_count",
		"locks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocks := _Locks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocks)

	if err != nil {
		return err
	}

	*o = Locks(varLocks)

	return err
}

type NullableLocks struct {
	value *Locks
	isSet bool
}

func (v NullableLocks) Get() *Locks {
	return v.value
}

func (v *NullableLocks) Set(val *Locks) {
	v.value = val
	v.isSet = true
}

func (v NullableLocks) IsSet() bool {
	return v.isSet
}

func (v *NullableLocks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocks(val *Locks) *NullableLocks {
	return &NullableLocks{value: val, isSet: true}
}

func (v NullableLocks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


