/*
Freqtrade API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freqtrade

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TradeModeType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TradeModeType{}

// TradeModeType struct for TradeModeType
type TradeModeType struct {
	TradingMode string `json:"trading_mode"`
	MarginMode  string `json:"margin_mode"`
}

type _TradeModeType TradeModeType

// NewTradeModeType instantiates a new TradeModeType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTradeModeType(tradingMode string, marginMode string) *TradeModeType {
	this := TradeModeType{}
	this.TradingMode = tradingMode
	this.MarginMode = marginMode
	return &this
}

// NewTradeModeTypeWithDefaults instantiates a new TradeModeType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTradeModeTypeWithDefaults() *TradeModeType {
	this := TradeModeType{}
	return &this
}

// GetTradingMode returns the TradingMode field value
func (o *TradeModeType) GetTradingMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TradingMode
}

// GetTradingModeOk returns a tuple with the TradingMode field value
// and a boolean to check if the value has been set.
func (o *TradeModeType) GetTradingModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TradingMode, true
}

// SetTradingMode sets field value
func (o *TradeModeType) SetTradingMode(v string) {
	o.TradingMode = v
}

// GetMarginMode returns the MarginMode field value
func (o *TradeModeType) GetMarginMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarginMode
}

// GetMarginModeOk returns a tuple with the MarginMode field value
// and a boolean to check if the value has been set.
func (o *TradeModeType) GetMarginModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarginMode, true
}

// SetMarginMode sets field value
func (o *TradeModeType) SetMarginMode(v string) {
	o.MarginMode = v
}

func (o TradeModeType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TradeModeType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trading_mode"] = o.TradingMode
	toSerialize["margin_mode"] = o.MarginMode
	return toSerialize, nil
}

func (o *TradeModeType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trading_mode",
		"margin_mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTradeModeType := _TradeModeType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTradeModeType)

	if err != nil {
		return err
	}

	*o = TradeModeType(varTradeModeType)

	return err
}

type NullableTradeModeType struct {
	value *TradeModeType
	isSet bool
}

func (v NullableTradeModeType) Get() *TradeModeType {
	return v.value
}

func (v *NullableTradeModeType) Set(val *TradeModeType) {
	v.value = val
	v.isSet = true
}

func (v NullableTradeModeType) IsSet() bool {
	return v.isSet
}

func (v *NullableTradeModeType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTradeModeType(val *TradeModeType) *NullableTradeModeType {
	return &NullableTradeModeType{value: val, isSet: true}
}

func (v NullableTradeModeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTradeModeType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
