// Code generated by ent, DO NOT EDIT.

package stripesubscription

import (
	"fmt"
	"time"
	"volaticloud/internal/enum"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the stripesubscription type in the database.
	Label = "stripe_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldStripeCustomerID holds the string denoting the stripe_customer_id field in the database.
	FieldStripeCustomerID = "stripe_customer_id"
	// FieldStripeSubscriptionID holds the string denoting the stripe_subscription_id field in the database.
	FieldStripeSubscriptionID = "stripe_subscription_id"
	// FieldStripePriceID holds the string denoting the stripe_price_id field in the database.
	FieldStripePriceID = "stripe_price_id"
	// FieldPlanName holds the string denoting the plan_name field in the database.
	FieldPlanName = "plan_name"
	// FieldMonthlyDeposit holds the string denoting the monthly_deposit field in the database.
	FieldMonthlyDeposit = "monthly_deposit"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFeatures holds the string denoting the features field in the database.
	FieldFeatures = "features"
	// FieldCurrentPeriodStart holds the string denoting the current_period_start field in the database.
	FieldCurrentPeriodStart = "current_period_start"
	// FieldCurrentPeriodEnd holds the string denoting the current_period_end field in the database.
	FieldCurrentPeriodEnd = "current_period_end"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the stripesubscription in the database.
	Table = "stripe_subscriptions"
)

// Columns holds all SQL columns for stripesubscription fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldStripeCustomerID,
	FieldStripeSubscriptionID,
	FieldStripePriceID,
	FieldPlanName,
	FieldMonthlyDeposit,
	FieldStatus,
	FieldFeatures,
	FieldCurrentPeriodStart,
	FieldCurrentPeriodEnd,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	OwnerIDValidator func(string) error
	// StripeCustomerIDValidator is a validator for the "stripe_customer_id" field. It is called by the builders before save.
	StripeCustomerIDValidator func(string) error
	// StripeSubscriptionIDValidator is a validator for the "stripe_subscription_id" field. It is called by the builders before save.
	StripeSubscriptionIDValidator func(string) error
	// StripePriceIDValidator is a validator for the "stripe_price_id" field. It is called by the builders before save.
	StripePriceIDValidator func(string) error
	// PlanNameValidator is a validator for the "plan_name" field. It is called by the builders before save.
	PlanNameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

const DefaultStatus enum.StripeSubStatus = "active"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s enum.StripeSubStatus) error {
	switch s {
	case "active", "past_due", "canceling", "canceled":
		return nil
	default:
		return fmt.Errorf("stripesubscription: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the StripeSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByStripeCustomerID orders the results by the stripe_customer_id field.
func ByStripeCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCustomerID, opts...).ToFunc()
}

// ByStripeSubscriptionID orders the results by the stripe_subscription_id field.
func ByStripeSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeSubscriptionID, opts...).ToFunc()
}

// ByStripePriceID orders the results by the stripe_price_id field.
func ByStripePriceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripePriceID, opts...).ToFunc()
}

// ByPlanName orders the results by the plan_name field.
func ByPlanName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanName, opts...).ToFunc()
}

// ByMonthlyDeposit orders the results by the monthly_deposit field.
func ByMonthlyDeposit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyDeposit, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCurrentPeriodStart orders the results by the current_period_start field.
func ByCurrentPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPeriodStart, opts...).ToFunc()
}

// ByCurrentPeriodEnd orders the results by the current_period_end field.
func ByCurrentPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPeriodEnd, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

var (
	// enum.StripeSubStatus must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.StripeSubStatus)(nil)
	// enum.StripeSubStatus must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.StripeSubStatus)(nil)
)
