// Code generated by ent, DO NOT EDIT.

package backtest

import (
	"fmt"
	"time"
	"volaticloud/internal/enum"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the backtest type in the database.
	Label = "backtest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldLogs holds the string denoting the logs field in the database.
	FieldLogs = "logs"
	// FieldStrategyID holds the string denoting the strategy_id field in the database.
	FieldStrategyID = "strategy_id"
	// FieldRunnerID holds the string denoting the runner_id field in the database.
	FieldRunnerID = "runner_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// EdgeStrategy holds the string denoting the strategy edge name in mutations.
	EdgeStrategy = "strategy"
	// EdgeRunner holds the string denoting the runner edge name in mutations.
	EdgeRunner = "runner"
	// Table holds the table name of the backtest in the database.
	Table = "backtests"
	// StrategyTable is the table that holds the strategy relation/edge.
	StrategyTable = "backtests"
	// StrategyInverseTable is the table name for the Strategy entity.
	// It exists in this package in order to avoid circular dependency with the "strategy" package.
	StrategyInverseTable = "strategies"
	// StrategyColumn is the table column denoting the strategy relation/edge.
	StrategyColumn = "strategy_id"
	// RunnerTable is the table that holds the runner relation/edge.
	RunnerTable = "backtests"
	// RunnerInverseTable is the table name for the BotRunner entity.
	// It exists in this package in order to avoid circular dependency with the "botrunner" package.
	RunnerInverseTable = "bot_runners"
	// RunnerColumn is the table column denoting the runner relation/edge.
	RunnerColumn = "runner_id"
)

// Columns holds all SQL columns for backtest fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldResult,
	FieldSummary,
	FieldErrorMessage,
	FieldLogs,
	FieldStrategyID,
	FieldRunnerID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCompletedAt,
	FieldStartDate,
	FieldEndDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

const DefaultStatus enum.TaskStatus = "pending"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s enum.TaskStatus) error {
	switch s {
	case "pending", "running", "completed", "failed":
		return nil
	default:
		return fmt.Errorf("backtest: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Backtest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByLogs orders the results by the logs field.
func ByLogs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogs, opts...).ToFunc()
}

// ByStrategyID orders the results by the strategy_id field.
func ByStrategyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyID, opts...).ToFunc()
}

// ByRunnerID orders the results by the runner_id field.
func ByRunnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByStrategyField orders the results by strategy field.
func ByStrategyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStrategyStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunnerField orders the results by runner field.
func ByRunnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunnerStep(), sql.OrderByField(field, opts...))
	}
}
func newStrategyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StrategyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, StrategyTable, StrategyColumn),
	)
}
func newRunnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunnerTable, RunnerColumn),
	)
}

var (
	// enum.TaskStatus must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.TaskStatus)(nil)
	// enum.TaskStatus must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.TaskStatus)(nil)
)
