// Code generated by ent, DO NOT EDIT.

package backtest

import (
	"anytrade/internal/ent/predicate"
	"anytrade/internal/enum"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldID, id))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldEndDate, v))
}

// Timeframe applies equality check predicate on the "timeframe" field. It's identical to TimeframeEQ.
func Timeframe(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldTimeframe, v))
}

// StakeAmount applies equality check predicate on the "stake_amount" field. It's identical to StakeAmountEQ.
func StakeAmount(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStakeAmount, v))
}

// StakeCurrency applies equality check predicate on the "stake_currency" field. It's identical to StakeCurrencyEQ.
func StakeCurrency(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStakeCurrency, v))
}

// RuntimeID applies equality check predicate on the "runtime_id" field. It's identical to RuntimeIDEQ.
func RuntimeID(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldRuntimeID, v))
}

// LogOutput applies equality check predicate on the "log_output" field. It's identical to LogOutputEQ.
func LogOutput(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldLogOutput, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldErrorMessage, v))
}

// StrategyID applies equality check predicate on the "strategy_id" field. It's identical to StrategyIDEQ.
func StrategyID(v uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStrategyID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldCompletedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v enum.TaskStatus) predicate.Backtest {
	vc := v
	return predicate.Backtest(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v enum.TaskStatus) predicate.Backtest {
	vc := v
	return predicate.Backtest(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...enum.TaskStatus) predicate.Backtest {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Backtest(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...enum.TaskStatus) predicate.Backtest {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Backtest(sql.FieldNotIn(FieldStatus, v...))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldEndDate, v))
}

// TimeframeEQ applies the EQ predicate on the "timeframe" field.
func TimeframeEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldTimeframe, v))
}

// TimeframeNEQ applies the NEQ predicate on the "timeframe" field.
func TimeframeNEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldTimeframe, v))
}

// TimeframeIn applies the In predicate on the "timeframe" field.
func TimeframeIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldTimeframe, vs...))
}

// TimeframeNotIn applies the NotIn predicate on the "timeframe" field.
func TimeframeNotIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldTimeframe, vs...))
}

// TimeframeGT applies the GT predicate on the "timeframe" field.
func TimeframeGT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldTimeframe, v))
}

// TimeframeGTE applies the GTE predicate on the "timeframe" field.
func TimeframeGTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldTimeframe, v))
}

// TimeframeLT applies the LT predicate on the "timeframe" field.
func TimeframeLT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldTimeframe, v))
}

// TimeframeLTE applies the LTE predicate on the "timeframe" field.
func TimeframeLTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldTimeframe, v))
}

// TimeframeContains applies the Contains predicate on the "timeframe" field.
func TimeframeContains(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContains(FieldTimeframe, v))
}

// TimeframeHasPrefix applies the HasPrefix predicate on the "timeframe" field.
func TimeframeHasPrefix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasPrefix(FieldTimeframe, v))
}

// TimeframeHasSuffix applies the HasSuffix predicate on the "timeframe" field.
func TimeframeHasSuffix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasSuffix(FieldTimeframe, v))
}

// TimeframeEqualFold applies the EqualFold predicate on the "timeframe" field.
func TimeframeEqualFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEqualFold(FieldTimeframe, v))
}

// TimeframeContainsFold applies the ContainsFold predicate on the "timeframe" field.
func TimeframeContainsFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContainsFold(FieldTimeframe, v))
}

// StakeAmountEQ applies the EQ predicate on the "stake_amount" field.
func StakeAmountEQ(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStakeAmount, v))
}

// StakeAmountNEQ applies the NEQ predicate on the "stake_amount" field.
func StakeAmountNEQ(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldStakeAmount, v))
}

// StakeAmountIn applies the In predicate on the "stake_amount" field.
func StakeAmountIn(vs ...float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldStakeAmount, vs...))
}

// StakeAmountNotIn applies the NotIn predicate on the "stake_amount" field.
func StakeAmountNotIn(vs ...float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldStakeAmount, vs...))
}

// StakeAmountGT applies the GT predicate on the "stake_amount" field.
func StakeAmountGT(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldStakeAmount, v))
}

// StakeAmountGTE applies the GTE predicate on the "stake_amount" field.
func StakeAmountGTE(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldStakeAmount, v))
}

// StakeAmountLT applies the LT predicate on the "stake_amount" field.
func StakeAmountLT(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldStakeAmount, v))
}

// StakeAmountLTE applies the LTE predicate on the "stake_amount" field.
func StakeAmountLTE(v float64) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldStakeAmount, v))
}

// StakeCurrencyEQ applies the EQ predicate on the "stake_currency" field.
func StakeCurrencyEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStakeCurrency, v))
}

// StakeCurrencyNEQ applies the NEQ predicate on the "stake_currency" field.
func StakeCurrencyNEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldStakeCurrency, v))
}

// StakeCurrencyIn applies the In predicate on the "stake_currency" field.
func StakeCurrencyIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldStakeCurrency, vs...))
}

// StakeCurrencyNotIn applies the NotIn predicate on the "stake_currency" field.
func StakeCurrencyNotIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldStakeCurrency, vs...))
}

// StakeCurrencyGT applies the GT predicate on the "stake_currency" field.
func StakeCurrencyGT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldStakeCurrency, v))
}

// StakeCurrencyGTE applies the GTE predicate on the "stake_currency" field.
func StakeCurrencyGTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldStakeCurrency, v))
}

// StakeCurrencyLT applies the LT predicate on the "stake_currency" field.
func StakeCurrencyLT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldStakeCurrency, v))
}

// StakeCurrencyLTE applies the LTE predicate on the "stake_currency" field.
func StakeCurrencyLTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldStakeCurrency, v))
}

// StakeCurrencyContains applies the Contains predicate on the "stake_currency" field.
func StakeCurrencyContains(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContains(FieldStakeCurrency, v))
}

// StakeCurrencyHasPrefix applies the HasPrefix predicate on the "stake_currency" field.
func StakeCurrencyHasPrefix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasPrefix(FieldStakeCurrency, v))
}

// StakeCurrencyHasSuffix applies the HasSuffix predicate on the "stake_currency" field.
func StakeCurrencyHasSuffix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasSuffix(FieldStakeCurrency, v))
}

// StakeCurrencyEqualFold applies the EqualFold predicate on the "stake_currency" field.
func StakeCurrencyEqualFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEqualFold(FieldStakeCurrency, v))
}

// StakeCurrencyContainsFold applies the ContainsFold predicate on the "stake_currency" field.
func StakeCurrencyContainsFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContainsFold(FieldStakeCurrency, v))
}

// ResultsIsNil applies the IsNil predicate on the "results" field.
func ResultsIsNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldIsNull(FieldResults))
}

// ResultsNotNil applies the NotNil predicate on the "results" field.
func ResultsNotNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldNotNull(FieldResults))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldNotNull(FieldConfig))
}

// RuntimeIDEQ applies the EQ predicate on the "runtime_id" field.
func RuntimeIDEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldRuntimeID, v))
}

// RuntimeIDNEQ applies the NEQ predicate on the "runtime_id" field.
func RuntimeIDNEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldRuntimeID, v))
}

// RuntimeIDIn applies the In predicate on the "runtime_id" field.
func RuntimeIDIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldRuntimeID, vs...))
}

// RuntimeIDNotIn applies the NotIn predicate on the "runtime_id" field.
func RuntimeIDNotIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldRuntimeID, vs...))
}

// RuntimeIDGT applies the GT predicate on the "runtime_id" field.
func RuntimeIDGT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldRuntimeID, v))
}

// RuntimeIDGTE applies the GTE predicate on the "runtime_id" field.
func RuntimeIDGTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldRuntimeID, v))
}

// RuntimeIDLT applies the LT predicate on the "runtime_id" field.
func RuntimeIDLT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldRuntimeID, v))
}

// RuntimeIDLTE applies the LTE predicate on the "runtime_id" field.
func RuntimeIDLTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldRuntimeID, v))
}

// RuntimeIDContains applies the Contains predicate on the "runtime_id" field.
func RuntimeIDContains(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContains(FieldRuntimeID, v))
}

// RuntimeIDHasPrefix applies the HasPrefix predicate on the "runtime_id" field.
func RuntimeIDHasPrefix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasPrefix(FieldRuntimeID, v))
}

// RuntimeIDHasSuffix applies the HasSuffix predicate on the "runtime_id" field.
func RuntimeIDHasSuffix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasSuffix(FieldRuntimeID, v))
}

// RuntimeIDIsNil applies the IsNil predicate on the "runtime_id" field.
func RuntimeIDIsNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldIsNull(FieldRuntimeID))
}

// RuntimeIDNotNil applies the NotNil predicate on the "runtime_id" field.
func RuntimeIDNotNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldNotNull(FieldRuntimeID))
}

// RuntimeIDEqualFold applies the EqualFold predicate on the "runtime_id" field.
func RuntimeIDEqualFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEqualFold(FieldRuntimeID, v))
}

// RuntimeIDContainsFold applies the ContainsFold predicate on the "runtime_id" field.
func RuntimeIDContainsFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContainsFold(FieldRuntimeID, v))
}

// LogOutputEQ applies the EQ predicate on the "log_output" field.
func LogOutputEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldLogOutput, v))
}

// LogOutputNEQ applies the NEQ predicate on the "log_output" field.
func LogOutputNEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldLogOutput, v))
}

// LogOutputIn applies the In predicate on the "log_output" field.
func LogOutputIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldLogOutput, vs...))
}

// LogOutputNotIn applies the NotIn predicate on the "log_output" field.
func LogOutputNotIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldLogOutput, vs...))
}

// LogOutputGT applies the GT predicate on the "log_output" field.
func LogOutputGT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldLogOutput, v))
}

// LogOutputGTE applies the GTE predicate on the "log_output" field.
func LogOutputGTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldLogOutput, v))
}

// LogOutputLT applies the LT predicate on the "log_output" field.
func LogOutputLT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldLogOutput, v))
}

// LogOutputLTE applies the LTE predicate on the "log_output" field.
func LogOutputLTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldLogOutput, v))
}

// LogOutputContains applies the Contains predicate on the "log_output" field.
func LogOutputContains(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContains(FieldLogOutput, v))
}

// LogOutputHasPrefix applies the HasPrefix predicate on the "log_output" field.
func LogOutputHasPrefix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasPrefix(FieldLogOutput, v))
}

// LogOutputHasSuffix applies the HasSuffix predicate on the "log_output" field.
func LogOutputHasSuffix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasSuffix(FieldLogOutput, v))
}

// LogOutputIsNil applies the IsNil predicate on the "log_output" field.
func LogOutputIsNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldIsNull(FieldLogOutput))
}

// LogOutputNotNil applies the NotNil predicate on the "log_output" field.
func LogOutputNotNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldNotNull(FieldLogOutput))
}

// LogOutputEqualFold applies the EqualFold predicate on the "log_output" field.
func LogOutputEqualFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEqualFold(FieldLogOutput, v))
}

// LogOutputContainsFold applies the ContainsFold predicate on the "log_output" field.
func LogOutputContainsFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContainsFold(FieldLogOutput, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Backtest {
	return predicate.Backtest(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StrategyIDEQ applies the EQ predicate on the "strategy_id" field.
func StrategyIDEQ(v uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldStrategyID, v))
}

// StrategyIDNEQ applies the NEQ predicate on the "strategy_id" field.
func StrategyIDNEQ(v uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldStrategyID, v))
}

// StrategyIDIn applies the In predicate on the "strategy_id" field.
func StrategyIDIn(vs ...uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldStrategyID, vs...))
}

// StrategyIDNotIn applies the NotIn predicate on the "strategy_id" field.
func StrategyIDNotIn(vs ...uuid.UUID) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldStrategyID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Backtest {
	return predicate.Backtest(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Backtest {
	return predicate.Backtest(sql.FieldNotNull(FieldCompletedAt))
}

// HasStrategy applies the HasEdge predicate on the "strategy" edge.
func HasStrategy() predicate.Backtest {
	return predicate.Backtest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StrategyTable, StrategyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStrategyWith applies the HasEdge predicate on the "strategy" edge with a given conditions (other predicates).
func HasStrategyWith(preds ...predicate.Strategy) predicate.Backtest {
	return predicate.Backtest(func(s *sql.Selector) {
		step := newStrategyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Backtest) predicate.Backtest {
	return predicate.Backtest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Backtest) predicate.Backtest {
	return predicate.Backtest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Backtest) predicate.Backtest {
	return predicate.Backtest(sql.NotPredicates(p))
}
