// Code generated by ent, DO NOT EDIT.

package bot

import (
	"anytrade/internal/enum"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the bot type in the database.
	Label = "bot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldContainerID holds the string denoting the container_id field in the database.
	FieldContainerID = "container_id"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldFreqtradeVersion holds the string denoting the freqtrade_version field in the database.
	FieldFreqtradeVersion = "freqtrade_version"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldExchangeID holds the string denoting the exchange_id field in the database.
	FieldExchangeID = "exchange_id"
	// FieldStrategyID holds the string denoting the strategy_id field in the database.
	FieldStrategyID = "strategy_id"
	// FieldRunnerID holds the string denoting the runner_id field in the database.
	FieldRunnerID = "runner_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeExchange holds the string denoting the exchange edge name in mutations.
	EdgeExchange = "exchange"
	// EdgeStrategy holds the string denoting the strategy edge name in mutations.
	EdgeStrategy = "strategy"
	// EdgeRunner holds the string denoting the runner edge name in mutations.
	EdgeRunner = "runner"
	// EdgeTrades holds the string denoting the trades edge name in mutations.
	EdgeTrades = "trades"
	// Table holds the table name of the bot in the database.
	Table = "bots"
	// ExchangeTable is the table that holds the exchange relation/edge.
	ExchangeTable = "bots"
	// ExchangeInverseTable is the table name for the Exchange entity.
	// It exists in this package in order to avoid circular dependency with the "exchange" package.
	ExchangeInverseTable = "exchanges"
	// ExchangeColumn is the table column denoting the exchange relation/edge.
	ExchangeColumn = "exchange_id"
	// StrategyTable is the table that holds the strategy relation/edge.
	StrategyTable = "bots"
	// StrategyInverseTable is the table name for the Strategy entity.
	// It exists in this package in order to avoid circular dependency with the "strategy" package.
	StrategyInverseTable = "strategies"
	// StrategyColumn is the table column denoting the strategy relation/edge.
	StrategyColumn = "strategy_id"
	// RunnerTable is the table that holds the runner relation/edge.
	RunnerTable = "bots"
	// RunnerInverseTable is the table name for the BotRunner entity.
	// It exists in this package in order to avoid circular dependency with the "botrunner" package.
	RunnerInverseTable = "bot_runners"
	// RunnerColumn is the table column denoting the runner relation/edge.
	RunnerColumn = "runner_id"
	// TradesTable is the table that holds the trades relation/edge.
	TradesTable = "trades"
	// TradesInverseTable is the table name for the Trade entity.
	// It exists in this package in order to avoid circular dependency with the "trade" package.
	TradesInverseTable = "trades"
	// TradesColumn is the table column denoting the trades relation/edge.
	TradesColumn = "bot_id"
)

// Columns holds all SQL columns for bot fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStatus,
	FieldMode,
	FieldContainerID,
	FieldConfig,
	FieldFreqtradeVersion,
	FieldLastSeenAt,
	FieldErrorMessage,
	FieldExchangeID,
	FieldStrategyID,
	FieldRunnerID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultFreqtradeVersion holds the default value on creation for the "freqtrade_version" field.
	DefaultFreqtradeVersion string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

const DefaultStatus enum.BotStatus = "creating"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s enum.BotStatus) error {
	switch s {
	case "creating", "running", "unhealthy", "stopped", "error", "backtesting", "hyperopt":
		return nil
	default:
		return fmt.Errorf("bot: invalid enum value for status field: %q", s)
	}
}

const DefaultMode enum.BotMode = "dry_run"

// ModeValidator is a validator for the "mode" field enum values. It is called by the builders before save.
func ModeValidator(m enum.BotMode) error {
	switch m {
	case "dry_run", "live":
		return nil
	default:
		return fmt.Errorf("bot: invalid enum value for mode field: %q", m)
	}
}

// OrderOption defines the ordering options for the Bot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByContainerID orders the results by the container_id field.
func ByContainerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContainerID, opts...).ToFunc()
}

// ByFreqtradeVersion orders the results by the freqtrade_version field.
func ByFreqtradeVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreqtradeVersion, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByExchangeID orders the results by the exchange_id field.
func ByExchangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeID, opts...).ToFunc()
}

// ByStrategyID orders the results by the strategy_id field.
func ByStrategyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyID, opts...).ToFunc()
}

// ByRunnerID orders the results by the runner_id field.
func ByRunnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExchangeField orders the results by exchange field.
func ByExchangeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExchangeStep(), sql.OrderByField(field, opts...))
	}
}

// ByStrategyField orders the results by strategy field.
func ByStrategyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStrategyStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunnerField orders the results by runner field.
func ByRunnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByTradesCount orders the results by trades count.
func ByTradesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTradesStep(), opts...)
	}
}

// ByTrades orders the results by trades terms.
func ByTrades(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTradesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newExchangeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExchangeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExchangeTable, ExchangeColumn),
	)
}
func newStrategyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StrategyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StrategyTable, StrategyColumn),
	)
}
func newRunnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunnerTable, RunnerColumn),
	)
}
func newTradesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TradesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TradesTable, TradesColumn),
	)
}

var (
	// enum.BotStatus must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.BotStatus)(nil)
	// enum.BotStatus must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.BotStatus)(nil)
)

var (
	// enum.BotMode must implement graphql.Marshaler.
	_ graphql.Marshaler = (*enum.BotMode)(nil)
	// enum.BotMode must implement graphql.Unmarshaler.
	_ graphql.Unmarshaler = (*enum.BotMode)(nil)
)
